const translations_en = {
    "page_title_index": "BCDeX - Windows Installation without USB",
    "nav_home": "Home",
    "nav_tutorial": "Tutorial",
    "nav_what_is": "What is BCDeX?",
    "nav_blog": "Blog",
    "nav_donations": "Donations",
    "nav_download": "Download",
    "nav_contact": "Contact",
    "nav_sobre_el_creador": "About the Creator",
    "index_hero_title": "Expert-Level Windows Installation.",
    "index_hero_subtitle": "BCDeX is the advanced automation tool that **eliminates the dependency on USB or DVD** to reinstall Windows (7-11). It guarantees a clean, secure, and **direct boot process from the hard drive**.",
    "index_hero_button": "Discover How It Works",
    "index_main_title": "BCDeX: Install Windows without using USB or DVD.",
    "index_main_slogan": "Installing Windows has never been easier!",
    "index_main_description": "The tool that radically simplifies the preparation of Windows installations directly from your hard drive. Forget physical media.",
    "index_main_download_button": "Download",
    "index_main_tutorial_button": "View Usage Guide",
    "index_features_title": "Main Features of BCDeX",
    "index_feature1_title": "Secure Partition Management",
    "index_feature1_description": "Uses native Windows tools (`diskpart.exe`) to create a temporary and dedicated partition, ensuring an isolated space for the operating system installation files.",
    "index_feature2_title": "BCD and Script Automation",
    "index_feature2_description": "Automatically and controllably executes PowerShell scripts for mounting ISO images and precisely configuring the system's boot data (BCD).",
    "index_feature3_title": "Optimized Extraction and Copy",
    "index_feature3_description": "Extracts only the essential files needed for the start of the installation from your Windows ISO (original or modified), optimizing preparation time and disk space usage.",
    "index_security_title": "Security: Clarification on False Positives",
    "index_security_description": "Due to the necessary manipulation of boot configuration (BCD) and partitions, some antivirus programs may report BCDeX as a \"false positive\". We assure you that the tool is completely safe and only executes fundamental Windows commands for its functionality.",
    "donations_supporters_title": "Thanks to the super CRACKS of the Community",
    "donations_supporters_placeholder": "Your name could be here!",
    "donations_supporter_1": "->Discover how to support BCDeX<-",
    "donations_cta_combo": "Your name could be here. Learn how",
    "donations_cta_here": "Here",
    "footer_creator": "PadeX - Content Creator and Developer",
    "footer_privacy": "Privacy",
    "footer_terms": "Terms and Conditions",
    "footer_copyright": "&copy; 2026 BCDeX. All rights reserved.",
    "tutorial_page_title": "BCDeX - Tutorial: User Guide",
    "tutorial_hero_title": "BCDeX in Action",
    "tutorial_hero_subtitle": "Tired of traditional methods? BCDeX revolutionizes the process by letting you create an installation drive directly on your hard drive. Watch the videos to see how easy and fast it is.",
    "tutorial_blog_articles_title": "More blog articles",
    "tutorial_blog_article1_title": "BCDeX 2.3: Turbo Mode",
    "tutorial_blog_article1_description": "Learn what Turbo Mode changes and how to re-enable features.",
    "tutorial_read_more": "Read more",
    "tutorial_blog_article2_title": "Optimize Windows 11 25H2",
    "tutorial_blog_article2_description": "Discover how to remove bloatware during installation.",
    "tutorial_blog_article3_title": "Installation from Partition",
    "tutorial_blog_article3_description": "Forget USB. Install Windows directly from the hard drive.",
    "tutorial_suggested_videos_title": "Suggested Videos",
    "tutorial_prev_video": "Previous video",
    "tutorial_next_video": "Next video",
    "tutorial_start_now_button": "Start using BCDeX now!",

    "info_page_title": "BCDeX - What Is It?",
    "info_header_title": "What is BCDeX?",
    "info_header_subtitle": "The tool that revolutionizes how you install Windows.",
    "info_section_title_main": "Expanded Definition",
    "info_text_definition_1": "BCDeX is an advanced software utility created to dramatically modernize and simplify the process of installing and reinstalling Windows operating systems. Its main innovation is that it completely eliminates the dependence on physical media such as USB drives or DVDs, allowing the entire process to be managed directly from the computer's hard drive.",
    "info_text_definition_2_italic": "In essence, BCDeX acts as an intelligent assistant that automates a series of complex technical tasks. This allows both novice and expert users to prepare a clean and efficient Windows installation with just a few clicks, reducing errors and saving time.",
    "info_section_title_features": "Detailed Features",
    "info_feature_1_title": "Secure Partition Management",
    "info_feature_1_desc": "BCDeX non-destructively creates a temporary partition on your hard drive. This isolated and secure space is where the Windows installation files will be housed, ensuring that your personal data is not at risk during the process.",
    "info_feature_2_title": "PowerShell Automation",
    "info_feature_2_desc": "The tool uses the power of PowerShell, the Windows scripting language, to run scripts that mount the ISO image, configure the boot environment (BCD), and prepare the system for installation, all without you needing to write a single line of code.",
    "info_feature_3_title": "Smart File Copying",
    "info_feature_3_desc": "Instead of copying an entire ISO image, BCDeX identifies and extracts only the essential files for booting and installation. This method dramatically optimizes preparation time and reduces the required disk space.",
    "info_section_title_safety": "Is It Safe to Use BCDeX?",
    "info_text_safety_1": "Yes, BCDeX is <strong class=\"text-red-600\">completely safe</strong>. The application has been designed with the utmost caution to interact with the operating system in a predictable and controlled manner, using only official Windows commands and tools.",
    "info_text_safety_warning": "Because it performs system-level operations (such as modifying partitions or editing the boot menu), some antiviruses may show a \"false positive\" alert. This is expected behavior for advanced administration tools. We guarantee that BCDeX contains no malware and only performs the documented and necessary actions to fulfill its function.",
    "info_cta_button": "Download BCDeX and simplify your life!",
    "feature_3_desc": "Instead of copying an entire ISO image, BCDeX identifies and extracts only the essential files for booting and installation. This method dramatically optimizes preparation time and reduces the required disk space.",
    "section_title_safety": "Is It Safe to Use BCDeX?",
    "text_safety_1": "Yes, BCDeX is <strong class=\"text-red-600\">completely safe</strong>. The application has been designed with the utmost caution to interact with the operating system in a predictable and controlled manner, using only official Windows commands and tools.",
    "text_safety_warning": "Because it performs system-level operations (such as modifying partitions or editing the boot menu), some antiviruses may show a \"false positive\" alert. This is expected behavior for advanced administration tools. We guarantee that BCDeX contains no malware and only performs the documented and necessary actions to fulfill its function.",
    "cta_button": "Download BCDeX and simplify your life!",

    "blog_page_title": "BCDeX Blog",
    "blog_header_title": "BCDeX Blog",
    "blog_header_subtitle": "Here you'll find detailed guides, tips, and the latest news about BCDeX and the world of operating system installation.",
    "read_more_link": "Read more <svg class=\"w-4 h-4\" data-lucide=\"arrow-right\"></svg>",
    "article_como_descargar_25h2_title": "How to Download and Install Windows 11 25H2",
    "article_como_descargar_25h2_description": "Step-by-step guide + video to download, prepare and install 25H2 with no hassle.",
    "article_modo_turbo_title": "BCDeX 2.3: Turbo Mode",
    "article_modo_turbo_description": "Learn what Turbo Mode changes and how to re-enable features.",
    "article_win11_25h2_title": "Optimize Windows 11 25H2",
    "article_win11_25h2_description": "Discover how to remove bloatware during installation.",
    "article_instalacion_particion_title": "Installation from Partition",
    "article_instalacion_particion_description": "Forget USB. Install Windows directly from the hard drive.",
    "article_uefi_bios_title": "UEFI and Legacy BIOS",
    "article_uefi_bios_description": "Differences, advantages and disadvantages of each boot mode.",
    "article_liberar_espacio_title": "Free Up Disk Space",
    "article_liberar_espacio_description": "Simple steps to optimize your PC and free up gigabytes of space.",
    "article_archivo_desatendido_title": "Unattended File Guide",
    "article_archivo_desatendido_description": "Learn how to automate Windows installation with an autounattend.xml file.",
    "article_sobre_el_creador_title": "How BCDeX Was Born",
    "article_sobre_el_creador_description": "Learn how BCDeX emerged, its goals, and how it evolved into an essential Windows installation tool.",

    "page_title": "BCDeX - What Is It?",
    "header_title": "What is BCDeX?",
    "header_subtitle": "The tool that revolutionizes how you install Windows.",
    "section_title_main": "Expanded Definition",
    "section_title_features": "Detailed Features",
    "feature_1_title": "Secure Partition Management",
    "feature_1_desc": "BCDeX non-destructively creates a temporary partition on your hard drive. This isolated and secure space is where the Windows installation files will be housed, ensuring that your personal data is not at risk during the process.",
    "feature_2_title": "PowerShell Automation",
    "feature_2_desc": "The tool uses the power of PowerShell, the Windows scripting language, to run scripts that mount the ISO image, configure the boot environment (BCD), and prepare the system for installation, all without you needing to write a single line of code.",
    "feature_3_title": "Smart File Copying",
    "text_definition_1": "BCDeX is an advanced software utility created to dramatically modernize and simplify the process of installing and reinstalling Windows operating systems. Its main innovation is that it completely eliminates the dependence on physical media such as USB drives or DVDs, allowing the entire process to be managed directly from the computer's hard drive.",
    "text_definition_2_italic": "In essence, BCDeX acts as an intelligent assistant that automates a series of complex technical tasks. This allows both novice and expert users to prepare a clean and efficient Windows installation with just a few clicks, reducing errors and saving time.",
    "article_25h2_page_title": "How to Download and Install Windows 11 25H2 (Step-by-step Guide + Video)",
    "article_25h2_back_to_all": "← Back to all articles",
    "article_25h2_header_title": "How to Download and Install Windows 11 25H2 (Step-by-step Guide + Video)",
    "article_25h2_intro": "Microsoft released Windows 11 version 25H2, an update many people want to install from scratch to avoid carrying over errors, bloatware, or old settings. In this article you have the video where I show exactly how to download, prepare, and install Windows 11 25H2 step by step without hassle.",
    "article_25h2_video_title": "Step-by-step video",
    "btn_download_bcdex": "Download BCDeX",
    "article_25h2_what_you_will_see": "What will you see in the tutorial?",
    "article_25h2_li_1": "How to download the official Windows 11 25H2 ISO",
    "article_25h2_li_2": "How to prepare the USB or installation media",
    "article_25h2_li_3": "How to start a clean installation from scratch",
    "article_25h2_li_4": "Which options to choose to avoid common errors",
    "article_25h2_li_5": "Tips to keep Windows clean and optimized from the first boot",
    "article_25h2_extra_note": "Additionally, during the video I explain important details so you don't run into compatibility issues or black screens, which often happens when installing Windows without knowing what to tweak.",
    "article_25h2_recommended_download": "Recommended download",
    "article_25h2_recommended_download_desc": "To simplify the process, I recommend using BCDeX: it prepares everything automatically and avoids typical errors. With one click you create the temporary partition, mount the ISO, and get the installation ready.",
    "other_articles_heading": "Other Blog Articles",
    "other_article_instalacion_particion": "Installation from Partition with BCDeX",
    "other_article_archivo_desatendido": "BCDeX – Unattended File Guide",
    "other_article_uefi_bios": "UEFI vs Legacy BIOS",
    "other_article_liberar_espacio": "Free Up Space and Optimize PC",
    "other_article_win11_25h2": "Windows 11 25H2: Less Bloatware, More Control",
    "other_article_optimizacion_win11": "Guide to Optimize Windows 11 During Installation",
    "article_modo_turbo_back_to_all": "← Back to all articles",
    "page_title_article_1": "BCDeX 2.3: Turbo Mode – What it deactivates and how to re-enable it"
,
    "article_1_title": "🚀 BCDeX 2.3: Turbo Mode – What it deactivates and how to re-enable it",
    "article_1_summary": "BCDeX 2.3's Turbo Mode is like a magic button: it turns off what Windows brings by default but you hardly ever use. This way your PC breathes and runs faster. If you miss something later (printing, VPN, scanner)? Don't worry, here you have how to turn it on again in seconds.",
    "section_1_title": "💡 What exactly does Turbo Mode do?",
    "section_1_intro": "This optimization focuses on freeing the maximum amount of resources without compromising the system's basic stability.",
    "turbo_point_1": "Creates a **Restore Point** before changing anything (safety first).",
    "turbo_point_2": "Turns off **rarely used services** (printing, maps, Xbox, sensors...).",
    "turbo_point_3": "Sets **network and update services** to manual so they're not constantly consuming resources.",
    "turbo_point_4": "Trims **telemetry** and user-experience scheduled tasks.",
    "turbo_point_5": "Enables the **Ultimate Performance** power plan and disables hibernation.",
    "turbo_point_6": "Adjusts **privacy**: goodbye to Recall, Copilot, and other data-sending features.",
    "section_2_title": "🔧 Did something you need turn off?",
    "section_2_intro": "Quick example: if your printer doesn't respond because the `Spooler` service is off. Solution: open **PowerShell** as administrator and paste the activation command.",
    "section_2_subtitle_1": "📋 List of basic services that Turbo Mode touches",
    "section_3_title": "📋 Other services you might find turned off",
    "section_3_intro": "Not all appear in every Windows. If you need them, turn them on with the command below (PowerShell as administrator).",
    "section_4_title": "🕒 Services on “pause” (Manual): they start automatically if you need them",
    "section_4_intro": "These services are set to 'Manual', which means Windows starts them automatically only when required by an app or feature, saving resources at startup. If you prefer them always ready, you can force Automatic mode:",
    "section_5_title": "🗑️ Application and component uninstallation",
    "section_5_intro": "Turbo Mode also removes some preinstalled apps and components considered 'bloatware' to lighten the system. Here I explain what is removed and how to get it back.",
    "section_5_subtitle_1": "Apps (Weather, Microsoft 365, Teams, To-Do)",
    "section_5_apps_desc": "Function: These are Microsoft apps that come with Windows. They are removed to clean the Start menu and free up space.<br>Reactivation: Search and install them for free from the <a href=\"https://www.microsoft.com/en-us/store/apps/windows\" target=\"_blank\" class=\"external-link\">Microsoft Store</a>.",
    "section_5_subtitle_2": "Microsoft Edge and its Reinstallation Lock",
    "section_5_edge_desc": "Function: Edge is removed in case you prefer another browser and don't want it consuming resources.<br>Reactivate Edge: Download the installer from the <a href=\"https://www.microsoft.com/en-us/edge\" target=\"_blank\" class=\"external-link\">official Microsoft Edge page</a>.",
    "section_5_edge_block_desc": "Reinstallation Lock: Turbo Mode activates a Registry lock to prevent Windows Update from reinstalling Edge. To disable this lock and allow Edge updates, run the following command in PowerShell as administrator:",
    "important_note_title": "🚨 Important: Variability in Windows!",
    "important_note_content": "Not all services exist in every Windows version. Windows 7, 10, and 11 do not provide exactly the same features, and things also change between editions (Home, Pro, Enterprise) and between builds/updates. **If you try a command and get an error that the service does not exist, that's okay:** it simply isn't present on your Windows. **Tip:** reactivate only what you truly need."
,
    "article_win11_25h2_back_to_all": "← Back to all articles",

    "section_win11_25h2_1_p1": "The main novelty comes via the Group Policy Editor. If you use Windows 11 Pro, simply press Win + R, type gpedit.msc and press Enter.",
    "section_win11_25h2_1_p2": "In the Group Policy Editor:",
    "section_win11_25h2_1_li1": "Go to <span class=\"font-semibold\">Computer Configuration → Administrative Templates → Windows Components</span>.",
    "section_win11_25h2_1_li2": "Find the new option called <span class=\"font-semibold\">Remove preinstalled apps</span>.",
    "section_win11_25h2_1_li3": "Double‑click it.",
    "section_win11_25h2_1_li4": "Select <span class=\"font-semibold\">Enabled</span>.",
    "section_win11_25h2_1_li5": "Save the changes.",
    "section_win11_25h2_1_li6": "Restart your PC. Done! Now you can uninstall apps like Paint, Media Player, Cortana, Sticky Notes, etc., directly from Settings.",
    "section_win11_25h2_1_p3": "If you use Windows 11 Home, unfortunately the Group Policy Editor is not officially available. There are unsupported methods to enable it or edit the registry, but they are not recommended for beginners.",

    "section_win11_25h2_2_p1": "The process is simple for Windows 11 Pro users. Just use the Group Policy Editor and enable the option to remove preinstalled apps.",
    "section_win11_25h2_2_p2": "<span class=\"font-semibold\">Computer Configuration > Windows Components > App Package Deployment</span>",
    "section_win11_25h2_2_p3": "For Windows 11 Home users, there is still no official solution. It's recommended to wait for future updates or use alternative methods with caution.",
    "section_win11_25h2_2_p4": "<span class=\"font-semibold\">Note:</span> Availability of this option may vary depending on your Windows 11 build. Make sure you're up to date.",
    "section_win11_25h2_2_p5": "After enabling the policy, go to <span class=\"font-semibold\">Settings → Apps → Installed apps</span> and remove the apps you want.",
    "section_win11_25h2_2_p6": "Remember: not all apps can be removed, but the list will be longer than ever.",

    "important_win11_25h2_li1": "Not all apps can be uninstalled. Some essential system components will remain protected.",
    "important_win11_25h2_li2": "Apps like Paint, Media Player, Cortana, Sticky Notes and some others can be removed. System apps such as File Explorer, Microsoft Store or Settings will remain protected.",
    "important_win11_25h2_li3": "Availability may vary depending on the build and region.",
    "important_win11_25h2_li4": "Always back up before removing important apps.",

    "section_win11_25h2_3_p1": "The new feature is expected in the Windows 11 25H2 update, scheduled for late 2026. Insider program users may get it earlier.",

    "section_win11_25h2_4_li1": "Less bloatware means a cleaner, faster system with more free space.",
    "section_win11_25h2_4_li2": "It gives users more control over what remains installed on their PC.",

    "section_win11_25h2_5_li1": "In addition to the apps mentioned, others may become removable in the future as Windows evolves.",
    "section_win11_25h2_5_li2": "The list of removable apps may grow in future updates.",
    "section_win11_25h2_5_li3": "Third‑party tools can still be useful for advanced removal.",
    "section_win11_25h2_5_li4": "Microsoft may revert or change this policy in future builds.",
    "section_win11_25h2_5_p1": "Stay tuned to the news and always read the release notes before updating.",

    "conclusion_win11_25h2_p1": "The Windows 11 25H2 update marks an important step in user control over the system.",
    "conclusion_win11_25h2_p2": "Removing bloatware has never been so easy — and official! Enjoy making Windows yours."
,
    "donations_page_title": "BCDeX: How the idea was born and who is behind the project",
    "donations_title": "Become a Project Partner",
    "donations_intro": "BCDeX is free and always will be thanks to the support of an incredible community. Your contribution is not just a donation: it's a fist bump to the project that already saved you from paying a technician, losing hours, or buying extra tools. It's an investment so that this tool —built by an enthusiast for enthusiasts— continues to exist and improve.",
    "donations_why_title": "Why is your support so important?",
    "donations_why_item1_title": "🚀 Drives new features",
    "donations_why_item1_text": "Every time Microsoft changes something, entire parts of the code must be rewritten from scratch. Your support allows time to be dedicated to those updates and to developing what the community requests: more compatibility, more automation, more customization.",
    "donations_why_item2_title": "🛡️ Ensures the project's continuity",
    "donations_why_item2_text": "Servers, domains, development and testing tools are not free. If no one contributes, the project ends like 90% of useful software that dies due to lack of support. If the community supports it, BCDeX remains free, clean, and without sponsors or spyware.",
    "donations_why_item3_title": "☕ Fuels the passion (and the developer)",
    "donations_why_item3_text": "This is a one‑developer project. Every donation literally turns into coffee, hours of code, bug fixing, and user support. It's a way to say ‘you helped me — here’s my real‑life fist bump’.",
    "donations_why_footer": "If BCDeX helped you, give back. If not, at least don't let it disappear for lack of support.",
    "donations_how_title": "Your Support Keeps BCDeX Going: Every Contribution Matters!",
    "donations_how_text": "BCDeX keeps growing thanks to you. Your donation—of any size—is vital to fund maintenance, ensure stable servers, and accelerate the development of new features. Help us keep moving forward! Thank you for being a pillar of our community.",

    "download_page_title": "BCDeX - Download",
    "download_header_title": "Download BCDeX",
    "download_header_subtitle": "You're one click away from simplifying your Windows installations forever.",
    "download_v23_title": "Version 2.3",
    "download_updated_on_label": "Updated on:",
    "download_features_title": "Main Features",
    "download_v23_b1": "Compatible with <strong>Windows 7</strong>, <strong>8</strong>, <strong>8.1</strong>, <strong>10</strong> and <strong>11</strong>",
    "download_v23_b2": "Creation of <strong>Bootable USB</strong> drives",
    "download_v23_b3": "<strong>Turbo Mode</strong>: Disables rarely used services to free system resources",
    "download_v23_b4": "Support for <strong>UEFI</strong> and <strong>Legacy</strong> boot",
    "download_v23_b5": "<strong>100% safe and malware‑free</strong>",
    "download_links_title": "Download Links",
    "download_server_1": "⬇️ Server #1",
    "download_server_2": "⬇️ Server #2",
    "download_server_3": "⬇️ Server #3",
    "download_changes_title": "Changes in this version",
    "download_changes_text": "Performance and stability improvements have been implemented.",
    "download_win7_compat_title": "Windows 7 Compatibility",
    "download_win7_compat_desc": ".rar package with .NET Framework 4.0 installers and x86/x64 cumulative updates required to run BCDeX on Windows 7.",
    "download_win7_package_btn": "Download Windows 7 package",
    "download_v13_title": "Version 1.3",
    "download_v13_b1": "Compatible with Windows 8, 10 and 11",
    "download_v13_b2": "Support for UEFI and Legacy boot",
    "download_v13_b3": "100% safe and malware‑free",
    "download_warning_title": "Important Notice",
    "download_warning_text": "BCDeX is a tool intended for users with some experience. Although we designed the app with great care, incorrect use could affect the system. We recommend following the instructions and using it wisely. For more information, see our <a href=\"terminos.html\" class=\"text-red-600 hover:underline\">Terms and Conditions</a>.",
    "download_contact_text": "If you have problems with the download or any suggestions, feel free to <a href=\"contacto.html\" class=\"text-red-600 hover:underline\">contact us</a>.",

    "contact_page_title": "Contact",
    "contact_title": "Contact",
    "contact_intro": "Do you have questions, suggestions, or need support?",
    "contact_intro_secondary": "These are the best ways to reach us:",
    "contact_youtube": "YouTube",
    "contact_facebook": "Facebook",
    "contact_discord": "Discord",
    "contact_email": "Email",
    "contact_tiktok": "TikTok",
    "contact_instagram": "Instagram",
    "contact_x": "X",
    "contact_support_title": "Support the project",
    "contact_support_text": "Every contribution, big or small, helps to keep improving BCDeX for the whole community.",
    "contact_support_button": "See donation options"
,
    "section_sobre_el_creador_1_p1": "It all started when one day, after installing Windows for the umpteenth time on different PCs (some without working USB ports, others with BIOS that don’t accept USB boot, others with very restrictive UEFIs...), I said to myself:",
    "section_sobre_el_creador_1_quote1": "Why does this have to be so complicated? What if I create a way to install Windows from the same hard drive, without pendrives, without DVDs, and without all the hassle?",
    "section_sobre_el_creador_1_p2": "That’s how I began by creating a small PowerShell script that simply created a secondary partition on the disk to act as a \"launcher\" for the Windows installation. It seemed like a good idea, until I realized something: you had to mount the ISO manually, copy the files one by one... and for many users that was a headache.",
    "section_sobre_el_creador_1_p3": "Then I remembered a phrase a teacher used to repeat to me during my studies:",
    "section_sobre_el_creador_1_quote2": "You must learn to program for dummies.",
    "section_sobre_el_creador_1_p4": "And he didn’t mean it offensively. What he meant was that when developing something, you have to think absolutely everything from the end user’s perspective, including those who have no idea about computing. The experience has to be so simple that anyone can do it without reading a manual.",
    "section_sobre_el_creador_1_p5": "That phrase clicked for me. And I set myself a goal: \"How can I make it so the user doesn’t even have to mount the ISO?\"",
    "page_title_article_sobre_el_creador": "BCDeX: How the idea was born and who is behind the project",
    "article_sobre_el_creador_back_link": "← Back to all articles",
    "article_sobre_el_creador_summary": "Hi, I'm José 'PadeX' 👋 and if you're reading this, you probably already know my application BCDeX, or at least it sounds familiar. In this post I want to tell you a little about the story behind the project. Because yes, although it may seem like a magic app that appears on your desktop and creates a bootable partition as if by magic... behind it there are many sleepless nights, failed tests and liters of coffee ☕.",
    "section_sobre_el_creador_2_title": "Learning by blows (and Google searches)",
    "section_sobre_el_creador_2_p1": "That's how I started working on automating the copying of the ISO directly from PowerShell. No need to mount it, no strange steps. Spoiler: it wasn't easy. I had to read a lot about ISO file structures, WIMs, extracting content directly without virtual drives... but in the end I managed to get everything to be done automatically.",
    "section_sobre_el_creador_2_p2": "So far so good. But I ran into another problem: the PowerShell console is not exactly the most user-friendly for many users. It's intimidating, it gives red errors, and it's not so clear what to do if something fails.",
    "section_sobre_el_creador_2_p3": "So I decided to take the next step: create a simple but functional graphical interface that would guide the user through the entire process —from creating the partition to copying the ISO and configuring the boot.",
    "section_sobre_el_creador_2_p4": "That's where what is now <strong>BCDeX</strong> was born.",
    "section_sobre_el_creador_3_title": "And where does the name \"BCDeX\" come from?",
    "section_sobre_el_creador_3_p1": "Once the application began to take shape, I needed a name. Something that reflected what it did, but also had a little personal identity.",
    "section_sobre_el_creador_3_p2": "That's where it occurred to me to combine two things: BCD, for the famous Boot Configuration Data that the app manipulates to create the Windows boot entries... and PadeX, which is the name of my YouTube channel, where I share many of these projects.",
    "section_sobre_el_creador_3_p3": "Thus the name BCDeX was born: a fusion of the technical and the personal. 😄",
    "section_sobre_el_creador_4_title": "And who is behind it?",
    "section_sobre_el_creador_4_p1": "As I told you before, I'm PadeX, and yes, I do everything: programmer, designer, tester, content creator and even technical support in the comments of my videos 😅.",
    "section_sobre_el_creador_4_p2": "Everything you see on this website, on the YouTube channel, and in the app, I do it myself (for now). With errors, with continuous improvements and with a great desire to keep moving forward.",
    "section_sobre_el_creador_4_p3": "BCDeX is not just a tool. It is the result of many tests, failures, learnings, and above all, an obsession to make life easier for anyone who wants to install Windows without complications.",
    "section_sobre_el_creador_5_title": "What's next?",
    "section_sobre_el_creador_5_p1": "Keep improving. I want to integrate new functions, such as post-installation optimizations, more compatibility, and some other surprise designed to leave your Windows ready and tuned from the first start.",
    "section_sobre_el_creador_5_p2": "That is why the support and contributions of those who use the app are also so important. Thanks to that I can continue to maintain the web, updating the tool and dedicating time to constantly improving it.",
    "section_sobre_el_creador_5_p3": "And if you are interested in knowing more or giving ideas, I invite you to follow me on my social networks, on <a href=\"https://www.youtube.com/@PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">YouTube</a>, <a href=\"https://www.instagram.com/padexchn/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Instagram</a>, <a href=\"https://www.tiktok.com/@padexch\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">TikTok</a>, <a href=\"https://x.com/PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">X</a>, <a href=\"https://www.facebook.com/PadeXch/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Facebook</a> and leave a comment there.",
    "section_sobre_el_creador_5_p4": "Thanks for being part of this. 💙",
    "section_sobre_el_creador_5_p5": "— <strong>PadeX</strong> 💻"
}
;