const translations_es = {
    'nav_home': 'Inicio',
    'nav_tutorial': 'Tutorial',
    'nav_what_is': 'Â¿BCDeX?',
    'nav_blog': 'Blog',
    'nav_donations': 'Donaciones',
    'nav_download': 'Descarga',
    'nav_contact': 'Contacto',
    'nav_sobre_el_creador': 'Sobre el Creador',
    'donations_supporters_title': 'Gracias a los super CRACKS de la Comunidad',
    'donations_supporters_p1': 'Agradecemos enormemente a todas las personas que han apoyado el proyecto. Â¡Gracias por hacer BCDeX posible!',
    'contributor_luiscm_name': 'luiscm152005',
    'contributor_luiscm_contribution': 'Por su apoyo continuo.',
    'contributor_luis_mora_name': 'Luis Mora',
    'contributor_luis_mora_contribution': 'Por su generosa contribuciÃ³n.',
    'contributor_patiduran_name': 'patiduran302',
    'contributor_patiduran_contribution': 'Por su valioso apoyo.',
    'contributor_longheiron_name': 'longheiron',
    'contributor_longheiron_contribution': 'Por su entusiasmo.',
    'contributor_antonyguaico_name': 'antonyguaico1483',
    'contributor_antonyguaico_contribution': 'Por su constante apoyo.',
    'contributor_isnel_name': 'Isnel',
    'contributor_isnel_contribution': 'Por su dedicaciÃ³n.',
    'contributor_antony_name': 'Antony 1483',
    'contributor_antony_contribution': 'Por su gran ayuda.',
    'contributor_erickzonexd_name': 'erickzonexd20',
    'contributor_erickzonexd_contribution': 'Por su colaboraciÃ³n.',
    'contributor_orutra_name': 'orutra.arevir.91',
    'contributor_orutra_contribution': 'Por su difusiÃ³n.',
    'contributor_juanchitortx_name': 'juanchitortx',
    'contributor_juanchitortx_contribution': 'Por su contribuciÃ³n.',
    'contributor_dean_gonzalez_name': 'Dean Gonzalez',
    'contributor_dean_gonzalez_contribution': 'Por su apoyo incondicional.',
    'contributor_celia_name': 'Celia bought',
    'contributor_celia_contribution': 'Por su generosidad.',
    'contributor_porfirio_name': 'porfirio118',
    'contributor_porfirio_contribution': 'Por su ayuda.',
    'contributor_armando_name': 'Armando Gomez',
    'contributor_armando_contribution': 'Por su colaboraciÃ³n.',
    'contributor_carlos_ley_name': 'Carlos Ley',
    'contributor_carlos_ley_contribution': 'Por su valioso apoyo.',
    'contributor_manny_name': 'Manny#0217',
    'contributor_manny_contribution': 'Por su gran ayuda.',
    'donations_supporters_placeholder': 'Â¡Tu nombre podrÃ­a estar aquÃ­!',
    'donations_supporter_1': 'Imagina aquÃ­ Tu nombre Crack',
    'footer_creator': 'PadeX - Creador de contenido y desarrollador',
    'footer_privacy': 'Privacidad',
    'footer_terms': 'TÃ©rminos y Condiciones',
    'footer_copyright': '&copy; 2026 BCDeX. Todos los derechos reservados.',
    'page_title_index': 'BCDeX - InstalaciÃ³n Windows sin USB',
    'index_hero_title': 'InstalaciÃ³n de Windows a Nivel Experto.',
    'index_hero_subtitle': 'BCDeX es la herramienta de automaciÃ³n avanzada que **elimina la dependencia de USB o DVD** para reinstalar Windows (7-11). Garantiza un proceso de arranque limpio, seguro y **directo desde el disco duro**.',
    'index_hero_button': 'Descubre CÃ³mo Funciona',
    'index_main_title': 'BCDeX: Instala Windows sin usar USB ni DVD.',
    'index_main_slogan': 'Â¡Instalar Windows nunca fue tan fÃ¡cil!',
    'index_main_description': 'La herramienta que simplifica radicalmente la preparaciÃ³n de instalaciones de Windows directamente desde tu disco duro. OlvÃ­date de los medios fÃ­sicos.',
    'index_main_download_button': 'Descargar',
    'index_main_tutorial_button': 'Ver GuÃ­a de Uso',
    'index_features_title': 'Funcionalidades Principales de BCDeX',
    'index_feature1_title': 'GestiÃ³n de Particiones Segura',
    'index_feature1_description': 'Utiliza herramientas nativas de Windows (`diskpart.exe`) para crear una particiÃ³n temporal y dedicada, asegurando un espacio aislado para los archivos de instalaciÃ³n del sistema operativo.',
    'index_feature2_title': 'AutomatizaciÃ³n BCD y Scripts',
    'index_feature2_description': 'Ejecuta de forma automÃ¡tica y controlada scripts de PowerShell para el montaje de imÃ¡genes ISO y la configuraciÃ³n precisa de los datos de arranque (BCD) del sistema.',
    'index_feature3_title': 'ExtracciÃ³n y Copia Optimizada',
    'index_feature3_description': 'Extrae Ãºnicamente los archivos esenciales necesarios para el inicio de la instalaciÃ³n desde su ISO de Windows (original o modificada), optimizando el tiempo de preparaciÃ³n y el uso del espacio en disco.',
    'index_security_title': 'Seguridad: AclaraciÃ³n sobre Falsos Positivos',
    'index_security_description': 'Debido a la manipulaciÃ³n necesaria de la configuraciÃ³n de arranque (BCD) y particiones, algunos antivirus pueden reportar a BCDeX como un "falso positivo". Aseguramos que la herramienta es completamente segura y solo ejecuta comandos fundamentales de Windows para su funcionalidad.',
    'page_title': 'Blog de BCDeX',
    'header_title': 'Blog de BCDeX',
    'header_subtitle': 'AquÃ­ encontrarÃ¡s guÃ­as detalladas, trucos y las Ãºltimas noticias sobre BCDeX y el mundo de la instalaciÃ³n de sistemas operativos.',
    'article_modo_turbo_title': 'BCDeX 2.3: Modo Turbo',
    'article_modo_turbo_description': 'Conoce quÃ© cambia Modo Turbo y cÃ³mo reactivar caracterÃ­sticas.',
    'article_modo_turbo_v30_title': 'BCDeX 3.0 Core: Modo Turbo Reforzado',
    'article_modo_turbo_v30_description': 'Qué optimiza la nueva versión, qué servicios toca y cómo restaurarlos si lo necesitas.',
    'article_win11_25h2_title': 'Optimiza Windows 11 25H2',
    'article_win11_25h2_description': 'Descubre cÃ³mo eliminar bloatware desde la instalaciÃ³n.',
    'article_instalacion_particion_title': 'InstalaciÃ³n desde ParticiÃ³n',
    'article_instalacion_particion_description': 'OlvÃ­date del USB. Instala Windows directamente desde el disco duro.',
    'article_uefi_bios_title': 'UEFI y BIOS Legacy',
    'article_uefi_bios_description': 'Diferencias, ventajas y desventajas de cada modo de arranque.',
    'article_liberar_espacio_title': 'Libera Espacio en Disco',
    'article_liberar_espacio_description': 'Pasos simples para optimizar tu PC y liberar gigabytes de espacio.',
    'article_archivo_desatendido_title': 'GuÃ­a Archivo Desatendido',
    'article_archivo_desatendido_description': 'Aprende a automatizar la instalaciÃ³n de Windows con un archivo autounattend.xml.',
    'article_sobre_el_creador_title': 'CÃ³mo naciÃ³ BCDeX',
    'article_sobre_el_creador_description': 'Conoce cÃ³mo surgiÃ³ BCDeX, sus objetivos y cÃ³mo ha evolucionado para convertirse en una herramienta esencial para la instalaciÃ³n de Windows.',
    'read_more_link': 'Leer mÃ¡s',
    "page_title_article_sobre_el_creador": "BCDeX: CÃ³mo naciÃ³ la idea y quiÃ©n estÃ¡ detrÃ¡s del proyecto",
    "article_sobre_el_creador_back_link": "â† Volver a todos los artÃ­culos",
    "article_sobre_el_creador_summary": "Hola, soy JosÃ© 'PadeX' ðŸ‘‹ y si estÃ¡s leyendo esto, seguramente ya conoces mi aplicaciÃ³n BCDeX, o al menos te suena. En este post quiero contarte un poco de la historia detrÃ¡s del proyecto. Porque sÃ­, aunque parezca una app mÃ¡gica que aparece en tu escritorio y te crea una particiÃ³n booteable como por arte de magia... detrÃ¡s hay muchas noches sin dormir, pruebas fallidas y litros de cafÃ© â˜•.",
    "section_sobre_el_creador_1_title": "Todo empezÃ³ por culpa de los 'WeSeBes'... y un script",
    "section_sobre_el_creador_1_p1": "Todo comenzÃ³ cuando un dÃ­a, despuÃ©s de instalar Windows por enÃ©sima vez en diferentes PCs (algunos sin puertos USB funcionales, otros sin BIOS que acepten arranque por USB, otros con UEFI sÃºper restrictivos...), me dije:",
    "section_sobre_el_creador_1_quote1": "â€œÂ¿Por quÃ© tiene que ser tan complicado esto? Â¿Y si creo una forma de instalar Windows <br>desde el mismo disco duro, sin pendrives, sin DVDs y sin tanto rollo?â€",
    "section_sobre_el_creador_1_p2": "AsÃ­ fue como empecÃ© creando un pequeÃ±o script en PowerShell que simplemente creaba una particiÃ³n secundaria en el disco para hacer de â€œlanzaderaâ€ de la instalaciÃ³n de Windows. ParecÃ­a buena idea, hasta que me di cuenta de algo: habÃ­a que montar la ISO manualmente, copiar los archivos uno por uno... y eso para muchos usuarios era un dolor de cabeza.",
    "section_sobre_el_creador_1_p3": "AhÃ­ recordÃ© una frase que me repetÃ­a un profesor en mis aÃ±os de estudio:",
    "section_sobre_el_creador_1_quote2": "â€œDeben aprender a programar para bobos.â€",
    "section_sobre_el_creador_1_p4": "Y no lo decÃ­a de forma ofensiva. Lo que querÃ­a decir era que al desarrollar algo, hay que pensar absolutamente todo desde el punto de vista del usuario final, incluso en el que no tiene ni idea de informÃ¡tica. La experiencia tiene que ser tan sencilla, que cualquiera pueda hacerlo sin leer un manual.",
    "section_sobre_el_creador_1_p5": "Esa frase me hizo clic. Y me propuse: â€œÂ¿CÃ³mo puedo hacer que el usuario ni siquiera tenga que montar la ISO?â€",
    "section_sobre_el_creador_2_title": "Aprendiendo a los golpes (y a Googleazos)",
    "section_sobre_el_creador_2_p1": "Fue asÃ­ como empecÃ© a trabajar en la automatizaciÃ³n del copiado de la ISO directamente desde PowerShell. Sin necesidad de montarla, sin pasos extraÃ±os. Spoiler: no fue fÃ¡cil. Me tocÃ³ leer bastante sobre estructuras de archivos ISO, WIMs, extraer contenido directamente sin unidades virtualesâ€¦ pero al final logrÃ© que todo se hiciera automÃ¡ticamente.",
    "section_sobre_el_creador_2_p2": "Hasta ahÃ­ todo iba bien. Pero me encontrÃ© con otro problema: la consola de PowerShell no es precisamente lo mÃ¡s amigable para muchos usuarios. Intimida, da errores en rojo, y no es tan claro quÃ© hacer si algo falla.",
    "section_sobre_el_creador_2_p3": "AsÃ­ que decidÃ­ dar el siguiente paso: crear una interfaz grÃ¡fica simple pero funcional, que guiara al usuario en todo el proceso â€”desde la creaciÃ³n de la particiÃ³n hasta el copiado de la ISO y la configuraciÃ³n del arranque.",
    "section_sobre_el_creador_2_p4": "AhÃ­ naciÃ³ lo que hoy es <strong>BCDeX</strong>.",
    "section_sobre_el_creador_3_title": "Â¿Y de dÃ³nde viene el nombre \"BCDeX\"?",
    "section_sobre_el_creador_3_p1": "Una vez la aplicaciÃ³n empezÃ³ a tomar forma, necesitaba un nombre. Algo que reflejara lo que hacÃ­a, pero que tambiÃ©n tuviera un poco de identidad personal.",
    "section_sobre_el_creador_3_p2": "AhÃ­ fue donde se me ocurriÃ³ combinar dos cosas: BCD, por el famoso Boot Configuration Data que manipula la app para crear las entradas de arranque de Windows... y PadeX, que es el nombre de mi canal de YouTube, donde comparto muchos de estos proyectos.",
    "section_sobre_el_creador_3_p3": "AsÃ­ naciÃ³ el nombre BCDeX: una fusiÃ³n de lo tÃ©cnico y lo personal. ðŸ˜„",
    "section_sobre_el_creador_4_title": "Â¿Y quiÃ©n estÃ¡ detrÃ¡s?",
    "section_sobre_el_creador_4_p1": "Como te dije antes, soy PadeX, y sÃ­, hago de todo: programador, diseÃ±ador, tester, creador de contenido y hasta soporte tÃ©cnico en los comentarios de mis videos ðŸ˜….",
    "section_sobre_el_creador_4_p2": "Todo lo que ves en esta web, en el canal de YouTube, y en la app, lo hago yo mismo (por ahora). Con errores, con mejoras continuas y con muchas ganas de seguir avanzando.",
    "section_sobre_el_creador_4_p3": "BCDeX no es solo una herramienta. Es el resultado de muchas pruebas, fracasos, aprendizajes, y sobre todo, de una obsesiÃ³n por hacerle la vida mÃ¡s fÃ¡cil a quien quiera instalar Windows sin complicaciones.",
    "section_sobre_el_creador_5_title": "Â¿QuÃ© sigue?",
    "section_sobre_el_creador_5_p1": "Seguir mejorando. Quiero integrar nuevas funciones, como optimizaciones post-instalaciÃ³n, mÃ¡s compatibilidad, y alguna que otra sorpresa pensada para dejar tu Windows listo y afinado desde el primer inicio.",
    "section_sobre_el_creador_5_p2": "Por eso tambiÃ©n es tan importante el apoyo y las contribuciones de quienes usan la app. Gracias a eso puedo seguir manteniendo la web, actualizando la herramienta y dedicando tiempo a mejorarla constantemente.",
    "section_sobre_el_creador_5_p3": "Y si te interesa saber mÃ¡s o dar ideas, te invito a seguirme en redes, en <a href=\"https://www.youtube.com/@PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">YouTube</a>, <a href=\"https://www.instagram.com/padexchn/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Instagram</a>, <a href=\"https://www.tiktok.com/@padexch\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">TikTok</a>, <a href=\"https://x.com/PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">X</a>, <a href=\"https://www.facebook.com/PadeXch/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Facebook</a> y dejar un comentario por allÃ­.",
    "section_sobre_el_creador_5_p4": "Gracias por ser parte de esto. ðŸ’™",
    "section_sobre_el_creador_5_p5": "â€” <strong>PadeX</strong> ðŸ’»",
    "download_page_title": "BCDeX - Descarga",
    "download_header_title": "Descarga BCDeX",
    "download_header_subtitle": "EstÃ¡s a un solo clic de simplificar tus instalaciones de Windows para siempre.",
    "download_v23_title": "VersiÃ³n 2.3",
    "download_updated_on_label": "Fecha de ActualizaciÃ³n:",
    "download_features_title": "CaracterÃ­sticas Principales",
    "download_v23_b1": "Compatible con <strong>Windows 7</strong>, <strong>8</strong>, <strong>8.1</strong>, <strong>10</strong> y <strong>11</strong>",
    "download_v23_b2": "CreaciÃ³n de Unidades <strong>USB Booteables</strong>",
    "download_v23_b3": "<strong>Modo Turbo</strong>: DesactivaciÃ³n de servicios poco usados liberando recursos del sistema",
    "download_v23_b4": "Soporte para arranque <strong>UEFI</strong> y <strong>Legacy</strong>",
    "download_v23_b5": "<strong>100% seguro y libre de malware</strong>",
    "download_links_title": "Enlaces de Descarga",
    "download_server_1": "â¬‡ï¸ Servidor #1",
    "download_server_2": "â¬‡ï¸ Servidor #2",
    "download_server_3": "â¬‡ï¸ Servidor #3",
    "download_changes_title": "Cambios en esta versiÃ³n",
    "download_changes_text": "Se han implementado mejoras de rendimiento y estabilidad.",
    "download_win7_compat_title": "Compatibilidad con Windows 7",
    "download_win7_compat_desc": "Paquete .rar con instaladores de .NET Framework 4.0 y actualizaciones acumulativas x86/x64 requeridas para ejecutar BCDeX en Windows 7.",
    "download_win7_package_btn": "Descargar paquete Windows 7",
    "download_v13_title": "VersiÃ³n 1.3",
    "download_v13_b1": "Compatible con Windows 8, 10 y 11",
    "download_v13_b2": "Soporte para arranque UEFI y Legacy",
    "download_v13_b3": "100% seguro y libre de malware",
    "download_warning_title": "Aviso Importante",
    "download_warning_text": "BCDeX es una herramienta pensada para usuarios con cierta experiencia. Aunque hemos diseÃ±ado la app con mucho cuidado, un uso incorrecto podrÃ­a afectar el sistema. Recomendamos seguir las instrucciones y usarla con criterio. Para mÃ¡s informaciÃ³n, consulta nuestros <a href=\"terminos.html\" class=\"text-red-600 hover:underline\">TÃ©rminos y Condiciones</a>.",
    "download_contact_text": "Si tienes problemas con la descarga o alguna sugerencia, no dudes en <a href=\"contacto.html\" class=\"text-red-600 hover:underline\">contactarnos</a>."
};
