const translations_es = {
    'nav_home': 'Inicio',
    'nav_tutorial': 'Tutorial',
    'nav_what_is': '¿BCDeX?',
    'nav_blog': 'Blog',
    'nav_donations': 'Donaciones',
    'nav_download': 'Descarga',
    'nav_contact': 'Contacto',
    'nav_sobre_el_creador': 'Sobre el Creador',
    'donations_supporters_title': 'Gracias a los super CRACKS de la Comunidad',
    'donations_supporters_p1': 'Agradecemos enormemente a todas las personas que han apoyado el proyecto. ¡Gracias por hacer BCDeX posible!',
    'contributor_luiscm_name': 'luiscm152005',
    'contributor_luiscm_contribution': 'Por su apoyo continuo.',
    'contributor_luis_mora_name': 'Luis Mora',
    'contributor_luis_mora_contribution': 'Por su generosa contribución.',
    'contributor_patiduran_name': 'patiduran302',
    'contributor_patiduran_contribution': 'Por su valioso apoyo.',
    'contributor_longheiron_name': 'longheiron',
    'contributor_longheiron_contribution': 'Por su entusiasmo.',
    'contributor_antonyguaico_name': 'antonyguaico1483',
    'contributor_antonyguaico_contribution': 'Por su constante apoyo.',
    'contributor_isnel_name': 'Isnel',
    'contributor_isnel_contribution': 'Por su dedicación.',
    'contributor_antony_name': 'Antony 1483',
    'contributor_antony_contribution': 'Por su gran ayuda.',
    'contributor_erickzonexd_name': 'erickzonexd20',
    'contributor_erickzonexd_contribution': 'Por su colaboración.',
    'contributor_orutra_name': 'orutra.arevir.91',
    'contributor_orutra_contribution': 'Por su difusión.',
    'contributor_juanchitortx_name': 'juanchitortx',
    'contributor_juanchitortx_contribution': 'Por su contribución.',
    'contributor_dean_gonzalez_name': 'Dean Gonzalez',
    'contributor_dean_gonzalez_contribution': 'Por su apoyo incondicional.',
    'contributor_celia_name': 'Celia bought',
    'contributor_celia_contribution': 'Por su generosidad.',
    'contributor_porfirio_name': 'porfirio118',
    'contributor_porfirio_contribution': 'Por su ayuda.',
    'contributor_armando_name': 'Armando Gomez',
    'contributor_armando_contribution': 'Por su colaboración.',
    'contributor_carlos_ley_name': 'Carlos Ley',
    'contributor_carlos_ley_contribution': 'Por su valioso apoyo.',
    'contributor_manny_name': 'Manny#0217',
    'contributor_manny_contribution': 'Por su gran ayuda.',
    'donations_supporters_placeholder': '¡Tu nombre podría estar aquí!',
    'donations_supporter_1': 'Imagina aquí Tu nombre Crack',
    'footer_creator': 'PadeX - Creador de contenido y desarrollador',
    'footer_privacy': 'Privacidad',
    'footer_terms': 'Términos y Condiciones',
    'footer_copyright': '&copy; 2026 BCDeX. Todos los derechos reservados.',
    'page_title_index': 'BCDeX - Instalación Windows sin USB',
    'index_hero_title': 'Instalación de Windows a Nivel Experto.',
    'index_hero_subtitle': 'BCDeX es la herramienta de automación avanzada que **elimina la dependencia de USB o DVD** para reinstalar Windows (7-11). Garantiza un proceso de arranque limpio, seguro y **directo desde el disco duro**.',
    'index_hero_button': 'Descubre Cómo Funciona',
    'index_main_title': 'BCDeX: Instala Windows sin usar USB ni DVD.',
    'index_main_slogan': '¡Instalar Windows nunca fue tan fácil!',
    'index_main_description': 'La herramienta que simplifica radicalmente la preparación de instalaciones de Windows directamente desde tu disco duro. Olvídate de los medios físicos.',
    'index_main_download_button': 'Descargar',
    'index_main_tutorial_button': 'Ver Guía de Uso',
    'index_features_title': 'Funcionalidades Principales de BCDeX',
    'index_feature1_title': 'Gestión de Particiones Segura',
    'index_feature1_description': 'Utiliza herramientas nativas de Windows (`diskpart.exe`) para crear una partición temporal y dedicada, asegurando un espacio aislado para los archivos de instalación del sistema operativo.',
    'index_feature2_title': 'Automatización BCD y Scripts',
    'index_feature2_description': 'Ejecuta de forma automática y controlada scripts de PowerShell para el montaje de imágenes ISO y la configuración precisa de los datos de arranque (BCD) del sistema.',
    'index_feature3_title': 'Extracción y Copia Optimizada',
    'index_feature3_description': 'Extrae únicamente los archivos esenciales necesarios para el inicio de la instalación desde su ISO de Windows (original o modificada), optimizando el tiempo de preparación y el uso del espacio en disco.',
    'index_security_title': 'Seguridad: Aclaración sobre Falsos Positivos',
    'index_security_description': 'Debido a la manipulación necesaria de la configuración de arranque (BCD) y particiones, algunos antivirus pueden reportar a BCDeX como un "falso positivo". Aseguramos que la herramienta es completamente segura y solo ejecuta comandos fundamentales de Windows para su funcionalidad.',
    'page_title': 'Blog de BCDeX',
    'header_title': 'Blog de BCDeX',
    'header_subtitle': 'Aquí encontrarás guías detalladas, trucos y las últimas noticias sobre BCDeX y el mundo de la instalación de sistemas operativos.',
    'article_modo_turbo_title': 'BCDeX 2.3: Modo Turbo',
    'article_modo_turbo_description': 'Conoce qué cambia Modo Turbo y cómo reactivar características.',
    'article_win11_25h2_title': 'Optimiza Windows 11 25H2',
    'article_win11_25h2_description': 'Descubre cómo eliminar bloatware desde la instalación.',
    'article_instalacion_particion_title': 'Instalación desde Partición',
    'article_instalacion_particion_description': 'Olvídate del USB. Instala Windows directamente desde el disco duro.',
    'article_uefi_bios_title': 'UEFI y BIOS Legacy',
    'article_uefi_bios_description': 'Diferencias, ventajas y desventajas de cada modo de arranque.',
    'article_liberar_espacio_title': 'Libera Espacio en Disco',
    'article_liberar_espacio_description': 'Pasos simples para optimizar tu PC y liberar gigabytes de espacio.',
    'article_archivo_desatendido_title': 'Guía Archivo Desatendido',
    'article_archivo_desatendido_description': 'Aprende a automatizar la instalación de Windows con un archivo autounattend.xml.',
    'article_sobre_el_creador_title': 'Cómo nació BCDeX',
    'article_sobre_el_creador_description': 'Conoce cómo surgió BCDeX, sus objetivos y cómo ha evolucionado para convertirse en una herramienta esencial para la instalación de Windows.',
    'read_more_link': 'Leer más',
    "page_title_article_sobre_el_creador": "BCDeX: Cómo nació la idea y quién está detrás del proyecto",
    "article_sobre_el_creador_back_link": "← Volver a todos los artículos",
    "article_sobre_el_creador_summary": "Hola, soy José 'PadeX' 👋 y si estás leyendo esto, seguramente ya conoces mi aplicación BCDeX, o al menos te suena. En este post quiero contarte un poco de la historia detrás del proyecto. Porque sí, aunque parezca una app mágica que aparece en tu escritorio y te crea una partición booteable como por arte de magia... detrás hay muchas noches sin dormir, pruebas fallidas y litros de café ☕.",
    "section_sobre_el_creador_1_title": "Todo empezó por culpa de los 'WeSeBes'... y un script",
    "section_sobre_el_creador_1_p1": "Todo comenzó cuando un día, después de instalar Windows por enésima vez en diferentes PCs (algunos sin puertos USB funcionales, otros sin BIOS que acepten arranque por USB, otros con UEFI súper restrictivos...), me dije:",
    "section_sobre_el_creador_1_quote1": "“¿Por qué tiene que ser tan complicado esto? ¿Y si creo una forma de instalar Windows <br>desde el mismo disco duro, sin pendrives, sin DVDs y sin tanto rollo?”",
    "section_sobre_el_creador_1_p2": "Así fue como empecé creando un pequeño script en PowerShell que simplemente creaba una partición secundaria en el disco para hacer de “lanzadera” de la instalación de Windows. Parecía buena idea, hasta que me di cuenta de algo: había que montar la ISO manualmente, copiar los archivos uno por uno... y eso para muchos usuarios era un dolor de cabeza.",
    "section_sobre_el_creador_1_p3": "Ahí recordé una frase que me repetía un profesor en mis años de estudio:",
    "section_sobre_el_creador_1_quote2": "“Deben aprender a programar para bobos.”",
    "section_sobre_el_creador_1_p4": "Y no lo decía de forma ofensiva. Lo que quería decir era que al desarrollar algo, hay que pensar absolutamente todo desde el punto de vista del usuario final, incluso en el que no tiene ni idea de informática. La experiencia tiene que ser tan sencilla, que cualquiera pueda hacerlo sin leer un manual.",
    "section_sobre_el_creador_1_p5": "Esa frase me hizo clic. Y me propuse: “¿Cómo puedo hacer que el usuario ni siquiera tenga que montar la ISO?”",
    "section_sobre_el_creador_2_title": "Aprendiendo a los golpes (y a Googleazos)",
    "section_sobre_el_creador_2_p1": "Fue así como empecé a trabajar en la automatización del copiado de la ISO directamente desde PowerShell. Sin necesidad de montarla, sin pasos extraños. Spoiler: no fue fácil. Me tocó leer bastante sobre estructuras de archivos ISO, WIMs, extraer contenido directamente sin unidades virtuales… pero al final logré que todo se hiciera automáticamente.",
    "section_sobre_el_creador_2_p2": "Hasta ahí todo iba bien. Pero me encontré con otro problema: la consola de PowerShell no es precisamente lo más amigable para muchos usuarios. Intimida, da errores en rojo, y no es tan claro qué hacer si algo falla.",
    "section_sobre_el_creador_2_p3": "Así que decidí dar el siguiente paso: crear una interfaz gráfica simple pero funcional, que guiara al usuario en todo el proceso —desde la creación de la partición hasta el copiado de la ISO y la configuración del arranque.",
    "section_sobre_el_creador_2_p4": "Ahí nació lo que hoy es <strong>BCDeX</strong>.",
    "section_sobre_el_creador_3_title": "¿Y de dónde viene el nombre \"BCDeX\"?",
    "section_sobre_el_creador_3_p1": "Una vez la aplicación empezó a tomar forma, necesitaba un nombre. Algo que reflejara lo que hacía, pero que también tuviera un poco de identidad personal.",
    "section_sobre_el_creador_3_p2": "Ahí fue donde se me ocurrió combinar dos cosas: BCD, por el famoso Boot Configuration Data que manipula la app para crear las entradas de arranque de Windows... y PadeX, que es el nombre de mi canal de YouTube, donde comparto muchos de estos proyectos.",
    "section_sobre_el_creador_3_p3": "Así nació el nombre BCDeX: una fusión de lo técnico y lo personal. 😄",
    "section_sobre_el_creador_4_title": "¿Y quién está detrás?",
    "section_sobre_el_creador_4_p1": "Como te dije antes, soy PadeX, y sí, hago de todo: programador, diseñador, tester, creador de contenido y hasta soporte técnico en los comentarios de mis videos 😅.",
    "section_sobre_el_creador_4_p2": "Todo lo que ves en esta web, en el canal de YouTube, y en la app, lo hago yo mismo (por ahora). Con errores, con mejoras continuas y con muchas ganas de seguir avanzando.",
    "section_sobre_el_creador_4_p3": "BCDeX no es solo una herramienta. Es el resultado de muchas pruebas, fracasos, aprendizajes, y sobre todo, de una obsesión por hacerle la vida más fácil a quien quiera instalar Windows sin complicaciones.",
    "section_sobre_el_creador_5_title": "¿Qué sigue?",
    "section_sobre_el_creador_5_p1": "Seguir mejorando. Quiero integrar nuevas funciones, como optimizaciones post-instalación, más compatibilidad, y alguna que otra sorpresa pensada para dejar tu Windows listo y afinado desde el primer inicio.",
    "section_sobre_el_creador_5_p2": "Por eso también es tan importante el apoyo y las contribuciones de quienes usan la app. Gracias a eso puedo seguir manteniendo la web, actualizando la herramienta y dedicando tiempo a mejorarla constantemente.",
    "section_sobre_el_creador_5_p3": "Y si te interesa saber más o dar ideas, te invito a seguirme en redes, en <a href=\"https://www.youtube.com/@PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">YouTube</a>, <a href=\"https://www.instagram.com/padexchn/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Instagram</a>, <a href=\"https://www.tiktok.com/@padexch\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">TikTok</a>, <a href=\"https://x.com/PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">X</a>, <a href=\"https://www.facebook.com/PadeXch/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Facebook</a> y dejar un comentario por allí.",
    "section_sobre_el_creador_5_p4": "Gracias por ser parte de esto. 💙",
    "section_sobre_el_creador_5_p5": "— <strong>PadeX</strong> 💻",
    "download_page_title": "BCDeX - Descarga",
    "download_header_title": "Descarga BCDeX",
    "download_header_subtitle": "Estás a un solo clic de simplificar tus instalaciones de Windows para siempre.",
    "download_v23_title": "Versión 2.3",
    "download_updated_on_label": "Fecha de Actualización:",
    "download_features_title": "Características Principales",
    "download_v23_b1": "Compatible con <strong>Windows 7</strong>, <strong>8</strong>, <strong>8.1</strong>, <strong>10</strong> y <strong>11</strong>",
    "download_v23_b2": "Creación de Unidades <strong>USB Booteables</strong>",
    "download_v23_b3": "<strong>Modo Turbo</strong>: Desactivación de servicios poco usados liberando recursos del sistema",
    "download_v23_b4": "Soporte para arranque <strong>UEFI</strong> y <strong>Legacy</strong>",
    "download_v23_b5": "<strong>100% seguro y libre de malware</strong>",
    "download_links_title": "Enlaces de Descarga",
    "download_server_1": "⬇️ Servidor #1",
    "download_server_2": "⬇️ Servidor #2",
    "download_server_3": "⬇️ Servidor #3",
    "download_changes_title": "Cambios en esta versión",
    "download_changes_text": "Se han implementado mejoras de rendimiento y estabilidad.",
    "download_win7_compat_title": "Compatibilidad con Windows 7",
    "download_win7_compat_desc": "Paquete .rar con instaladores de .NET Framework 4.0 y actualizaciones acumulativas x86/x64 requeridas para ejecutar BCDeX en Windows 7.",
    "download_win7_package_btn": "Descargar paquete Windows 7",
    "download_v13_title": "Versión 1.3",
    "download_v13_b1": "Compatible con Windows 8, 10 y 11",
    "download_v13_b2": "Soporte para arranque UEFI y Legacy",
    "download_v13_b3": "100% seguro y libre de malware",
    "download_warning_title": "Aviso Importante",
    "download_warning_text": "BCDeX es una herramienta pensada para usuarios con cierta experiencia. Aunque hemos diseñado la app con mucho cuidado, un uso incorrecto podría afectar el sistema. Recomendamos seguir las instrucciones y usarla con criterio. Para más información, consulta nuestros <a href=\"terminos.html\" class=\"text-red-600 hover:underline\">Términos y Condiciones</a>.",
    "download_contact_text": "Si tienes problemas con la descarga o alguna sugerencia, no dudes en <a href=\"contacto.html\" class=\"text-red-600 hover:underline\">contactarnos</a>."
};