const translations_pt_br = {
    "page_title_index": "BCDeX - Instalação do Windows sem USB",
    "nav_home": "Início",
    "nav_tutorial": "Tutorial",
    "nav_what_is": "O que é BCDeX?",
    "nav_blog": "Blog",
    "nav_donations": "Doações",
    "nav_download": "Download",
    "nav_contact": "Contato",
    "nav_sobre_el_creador": "Sobre o Criador",
    "index_badge_hero": "BCDeX 3.2 Advanced • A forma moderna de instalar o Windows",
    "index_main_title": "Instale ou Reinstale o Windows sem Usar USB ou DVD.",
    "index_main_slogan": "Instalar o Windows nunca foi tão rápido, seguro e fácil!",
    "index_main_description": "O BCDeX é a ferramenta que automatiza completamente a instalação do Windows (11, 10, 8.1, 7). Cria partições de boot diretas no disco rígido, prepara USBs universais com um clique e otimiza seu PC com o Modo Turbo. 100% automático, seguro e reversível.",
    "index_hero_bullet1": "Inicialização direta a partir de partição interna no disco rígido",
    "index_hero_bullet2": "USB inicializável universal compatível com UEFI e BIOS Legacy",
    "index_hero_bullet3": "100% Reversível: recupere seu espaço com 1 clique ao terminar",
    "index_main_download_button": "Baixar Grátis",
    "index_main_tutorial_button": "Ver Guia de Uso",
    "index_steps_title": "Como Funciona o BCDeX?",
    "index_steps_subtitle": "Reinstalar seu PC é tão simples quanto 3 passos claros, sem comandos nem configurações complexas.",
    "index_step1_title": "1. Selecione sua ISO do Windows",
    "index_step1_desc": "Carregue qualquer imagem ISO oficial ou personalizada. O BCDeX analisa o arquivo e valida o espaço disponível automaticamente.",
    "index_step2_title": "2. O BCDeX Prepara Tudo",
    "index_step2_desc": "O programa cria a partição segura, extrai os arquivos essenciais e configura o menu de inicialização do Windows (BCD) em segundos.",
    "index_step3_title": "3. Reinicie e Instale",
    "index_step3_desc": "Seu computador reinicia diretamente no instalador do Windows. Quando terminar, execute o BCDeX para remover a partição e recuperar o espaço.",
    "index_features_title": "Por que Escolher o BCDeX?",
    "index_features_subtitle": "Tecnologia pensada para economizar tempo, evitar erros técnicos e proteger seu hardware.",
    "index_feat1_title": "Zero Dependência de USB",
    "index_feat1_desc": "Não precisa procurar pen drives nem se preocupar com portas USB que não funcionam. Tudo acontece dentro do seu disco com velocidade máxima.",
    "index_feat2_title": "Criador de USB Universal",
    "index_feat2_desc": "Se preferir usar USB, o BCDeX cria unidades inicializáveis compatíveis tanto com BIOS Legacy (MBR) quanto com UEFI moderno (GPT).",
    "index_feat3_title": "Modo Turbo Otimizado",
    "index_feat3_desc": "Desativa processos desnecessários e telemetrias para que o instalador e o Windows rodem com máxima fluidez e rapidez.",
    "index_feat4_title": "100% Reversível e Limpo",
    "index_feat4_desc": "Ao concluir a instalação, a opção 'Desfazer alterações' exclui a partição temporária e devolve todo o espaço ao disco principal.",
    "index_feat5_title": "Sem Comandos Complexos",
    "index_feat5_desc": "Não precisa abrir o CMD nem usar comandos complicados do diskpart ou bcdedit. A interface gráfica guia todo o processo.",
    "index_feat6_title": "Pula Bloqueios e Requisitos",
    "index_feat6_desc": "Permite instalar o Windows 11 omitindo checagens de TPM e Secure Boot em computadores compatíveis com um único clique.",
    "index_comparison_title": "Método Tradicional vs. Método BCDeX",
    "index_comparison_subtitle": "Descubra por que milhares de usuários deixaram de usar ferramentas antigas.",
    "index_comp_col_feature": "Recurso / Vantagem",
    "index_comp_col_traditional": "Método Tradicional (USB)",
    "index_comp_col_bcdex": "Com BCDeX",
    "index_comp_row1_title": "Requer pen drive ou DVD externo",
    "index_comp_row1_trad": "Sim, obrigatório (mínimo 8 GB)",
    "index_comp_row1_bcdex": "Não necessário (opcional)",
    "index_comp_row2_title": "Velocidade de preparação",
    "index_comp_row2_trad": "Lenta (limitada pela velocidade do USB)",
    "index_comp_row2_bcdex": "Ultrarrápida (velocidade interna NVMe/SSD)",
    "index_comp_row3_title": "Risco de erro no boot",
    "index_comp_row3_trad": "Alto (falhas de BIOS/UEFI/Porta)",
    "index_comp_row3_bcdex": "Mínimo (arranque nativo por BCD)",
    "index_comp_row4_title": "Reversibilidade do espaço",
    "index_comp_row4_trad": "Formatar o pen drive manualmente",
    "index_comp_row4_bcdex": "1 Clique para restaurar seu disco",
    "index_comp_row5_title": "Otimização e Modo Turbo",
    "index_comp_row5_trad": "Não incluído",
    "index_comp_row5_bcdex": "Integrado no próprio aplicativo",
    "index_security_badge": "Transparência & Segurança",
    "index_security_title": "100% Seguro, Aberto e Sem Malware",
    "index_security_desc": "O BCDeX interage diretamente com o gerenciador de inicialização oficial do Windows (BCD) e comandos nativos do sistema. Por realizar operações avançadas de partição, alguns antivírus podem emitir alertas de falso positivo. Garantimos que o software é 100% limpo, sem spyware nem anúncios ocultos.",
    "index_security_btn": "Ver Termos de Uso e Segurança",
    "index_cta_title": "Pronto para Reinstalar o Windows sem Complicações?",
    "index_cta_subtitle": "Baixe o BCDeX hoje mesmo e aproveite a forma mais rápida, limpa e moderna de preparar seu sistema operacional.",
    "footer_creator": "PadeX - Criador de conteúdo e desenvolvedor",
    "footer_privacy": "Privacidade",
    "footer_terms": "Termos e Condições",
    "footer_copyright": "&copy; 2026 BCDeX. Todos os direitos reservados.",
    "donations_supporters_title": "Super CRACKS",
    "donations_cta_combo": "Seu nome e avatar também podem estar aqui. Descubra como",
    "donations_cta_here": "Apoiar o BCDeX",
    "tutorial_page_title": "BCDeX - Tutorial: Guia de Uso",
    "tutorial_hero_title": "BCDeX em Ação",
    "tutorial_hero_subtitle": "Cansado dos métodos tradicionais? O BCDeX revoluciona o processo permitindo criar uma unidade de instalação diretamente no seu disco rígido.",
    "tutorial_blog_articles_title": "Mais artigos do blog",
    "tutorial_blog_article1_title": "BCDeX 2.3: Modo Turbo",
    "tutorial_blog_article1_description": "Saiba o que o Modo Turbo altera e como reativar recursos.",
    "tutorial_blog_article2_title": "Otimize o Windows 11 25H2",
    "tutorial_blog_article2_description": "Descubra como remover bloatware desde a instalação.",
    "tutorial_blog_article3_title": "Instalação a partir de Partição",
    "tutorial_blog_article3_description": "Esqueça o USB. Instale o Windows diretamente do disco rígido.",
    "tutorial_read_more": "Ler mais",
    "tutorial_suggested_videos_title": "Vídeos Sugeridos",
    "tutorial_prev_video": "Vídeo anterior",
    "tutorial_next_video": "Próximo vídeo",
    "tutorial_start_now_button": "Comece a usar o BCDeX agora!",
    "page_title": "BCDeX - O que é?",
    "header_title": "O que é o BCDeX?",
    "header_subtitle": "A ferramenta que revoluciona a sua maneira de instalar o Windows.",
    "section_title_main": "Definição Expandida",
    "text_definition_1": "O BCDeX é um utilitário de software avançado, criado para modernizar e simplificar drasticamente o processo de instalação e reinstalação de sistemas operacionais Windows. Sua principal inovação é eliminar completamente a dependência de mídias físicas como pen drives ou DVDs, permitindo que todo o processo seja gerenciado diretamente do disco rígido.",
    "text_definition_2_italic": "Em essência, o BCDeX funciona como um assistente inteligente que automatiza uma série de tarefas técnicas complexas. Isso permite que tanto iniciantes quanto especialistas preparem uma instalação limpa e eficiente do Windows com apenas alguns cliques, reduzindo erros e economizando tempo.",
    "section_title_features": "Funcionalidades Detalhadas",
    "feature_1_title": "Instalação por Partição Interna (Direct-to-Disk)",
    "feature_1_desc": "O BCDeX cria um ambiente de boot temporário e não destrutivo direto no seu disco rígido. Extrai os arquivos essenciais da ISO e configura o gerenciador de inicialização (BCD), permitindo instalar o Windows sem pendrive ou DVD.",
    "feature_2_title": "Criação de USB Inicializável Universal",
    "feature_2_desc": "Transforme qualquer pendrive em um instalador de alta compatibilidade. O aplicativo extrai e prepara a estrutura nativa com suporte híbrido para placas-mãe UEFI modernas (GPT) e sistemas BIOS Legacy legados (MBR).",
    "feature_3_title": "USB Multi-ISO com Tecnologia Ventoy (v3.2 Advanced)",
    "feature_3_desc": "Próxima grande inovação na versão 3.2 Advanced: integra a tecnologia do Ventoy to Disk para inicializar múltiplos sistemas em um único pendrive. Nesse modo você copia os arquivos ISO completos do Windows ou Linux diretamente, sem necessidade de descompactar.",
    "info_compatibility_title": "Compatibilidade Testada e Homologada (v3.2 Advanced)",
    "section_title_safety": "É seguro usar o BCDeX?",
    "text_safety_1": "Sim, o BCDeX é <strong class=\"text-emerald-400\">completamente seguro</strong>. Ele foi projetado para interagir com o sistema de forma previsível e controlada, usando apenas comandos e ferramentas oficiais do Windows.",
    "text_safety_warning": "Por realizar operações em nível de sistema (como modificar partições ou editar o menu de inicialização), alguns antivírus podem exibir um alerta de \"falso positivo\". Isso é esperado em ferramentas de administração avançada. Garantizamos que o BCDeX não contém malware e realiza apenas as ações necessárias e documentadas.",
    "cta_button": "Baixe o BCDeX e simplifique sua vida!",
    "blog_page_title": "Blog do BCDeX",
    "blog_header_title": "Blog do BCDeX",
    "blog_header_subtitle": "Aqui você encontrará guias detalhados, dicas e as últimas notícias sobre o BCDeX e o mundo da instalação de sistemas operacionais.",
    "read_more_link": "Ler mais",
    "article_como_descargar_25h2_title": "Como baixar e instalar o Windows 11 25H2",
    "article_como_descargar_25h2_description": "Guia passo a passo + vídeo para baixar, preparar e instalar o 25H2 sem complicações.",
    "article_modo_turbo_title": "BCDeX 2.3: Modo Turbo",
    "article_modo_turbo_description": "Saiba o que muda com o Modo Turbo e como reativar recursos.",
    "article_modo_turbo_v30_title": "BCDeX 3.0 Core: Modo Turbo Reforçado",
    "article_modo_turbo_v30_description": "Veja o que a nova versão otimiza, quais serviços ela altera e como restaurá-los se precisar.",
    "article_win11_25h2_title": "Otimize o Windows 11 25H2",
    "article_win11_25h2_description": "Descubra como remover bloatware durante a instalação.",
    "article_instalacion_particion_title": "Instalação a partir de Partição",
    "article_instalacion_particion_description": "Esqueça o USB. Instale o Windows diretamente do disco rígido.",
    "article_uefi_bios_title": "UEFI e BIOS Legacy",
    "article_uefi_bios_description": "Diferenças, vantagens e desvantagens de cada modo de boot.",
    "article_liberar_espacio_title": "Liberar Espaço em Disco",
    "article_liberar_espacio_description": "Passos simples para otimizar seu PC e liberar gigabytes de espaço.",
    "article_archivo_desatendido_title": "Guia de Arquivo Desassistido",
    "article_archivo_desatendido_description": "Aprenda a automatizar a instalação do Windows com um arquivo autounattend.xml.",
    "article_sobre_el_creador_title": "Como nasceu o BCDeX",
    "article_sobre_el_creador_description": "Conheça como surgiu o BCDeX, seus objetivos e como ele se tornou uma ferramenta essencial.",
    "donations_page_title": "BCDeX - Apoie o Projeto e Mural de Honra",
    "donations_title": "Torne-se um Apoiador do Projeto",
    "donations_intro": "O BCDeX é gratuito e sempre será graças ao apoio de uma comunidade incrível. Sua contribuição mantém o projeto vivo e em constante melhoria.",
    "donations_why_title": "Por que o seu apoio é tão importante?",
    "donations_why_item1_title": "🚀 Impulsiona novas funções",
    "donations_why_item1_text": "Sempre que a Microsoft altera algo, reescrevemos partes inteiras do código. Seu apoio permite dedicar tempo a essas atualizações.",
    "donations_why_item2_title": "🛡️ Garante a continuidade do projeto",
    "donations_why_item2_text": "Servidores, domínios e ferramentas não são gratuitos. Seu apoio garante que o BCDeX permaneça gratuito, limpo e sem spyware.",
    "donations_why_item3_title": "☕ Alimenta a paixão (e o desenvolvedor)",
    "donations_why_item3_text": "Este é um projeto de um desenvolvedor solo. Cada doação se converte em café, horas de código e suporte aos usuários.",
    "donations_why_footer": "Se o BCDeX te ajudou, retribua. Não deixe o projeto desaparecer por falta de apoio.",
    "donations_how_title": "Seu Apoio Mantém o BCDeX: Cada Contribuição Conta!",
    "donations_how_text": "O BCDeX continua crescendo graças a você. Sua doação é vital para financiar a infraestrutura e acelerar novos recursos.",
    "download_page_title": "BCDeX - Download Oficial",
    "download_header_title": "Baixar BCDeX",
    "download_header_subtitle": "Você está a um clique de simplificar suas instalações do Windows para sempre. Escolha sua versão.",
    "download_v32_title": "BCDeX 3.2 Advanced",
    "download_v30_title": "BCDeX 3.0 Core",
    "download_v23_title": "BCDeX 2.3",
    "download_v23_btn": "Ver Downloads v2.3",
    "download_updated_on_label": "Atualizado em:",
    "download_features_title": "Características Principais",
    "download_v23_b1": "Compatível com <strong>Windows 7</strong>, <strong>8</strong>, <strong>8.1</strong>, <strong>10</strong> e <strong>11</strong>",
    "download_v23_b2": "Criação de unidades <strong>USB inicializáveis</strong>",
    "download_v23_b3": "<strong>Modo Turbo</strong> para liberar recursos do sistema",
    "download_v23_b4": "Suporte para inicialização <strong>UEFI</strong> e <strong>Legacy</strong>",
    "download_links_title": "Servidores de Download",
    "download_server_1": "⬇️ Servidor #1",
    "download_server_2": "⬇️ Servidor #2",
    "download_win7_compat_title": "Instalando no Windows 7?",
    "download_win7_compat_desc": "Baixe o pacote com .NET Framework 4.0 e atualizações necessárias.",
    "download_win7_package_btn": "Baixar Pacote Windows 7",
    "download_warning_title": "Aviso Importante & Segurança",
    "download_warning_text": "O BCDeX interage diretamente com o gerenciador de boot (BCD). Embora 100% seguro, alguns antivírus emitem alertas de falso positivo por suas funções avançadas.",
    "contact_page_title": "BCDeX - Contato e Canais Oficiais",
    "contact_title": "Contato",
    "contact_intro": "Tem dúvidas, sugestões ou precisa de suporte?",
    "contact_intro_secondary": "Estas são as melhores formas de se comunicar conosco:",
    "contact_youtube": "YouTube",
    "contact_discord": "Discord",
    "contact_email": "E-mail",
    "contact_facebook": "Facebook",
    "contact_tiktok": "TikTok",
    "contact_instagram": "Instagram",
    "contact_x": "X (Twitter)",
    "contact_support_title": "Apoie o Projeto",
    "contact_support_text": "Toda contribuição, grande ou pequena, ajuda a continuar desenvolvendo o BCDeX para toda a comunidade.",
    "contact_support_button": "Ver opções de doação"
};
