const translations_pt_br = {
    "page_title_index": "BCDeX - InstalaÃ§Ã£o do Windows sem USB",
    "nav_home": "InÃ­cio",
    "nav_tutorial": "Tutorial",
    "nav_what_is": "O que Ã© BCDeX?",
    "nav_blog": "Blog",
    "nav_donations": "DoaÃ§Ãµes",
    "nav_download": "Download",
    "nav_contact": "Contato",
    "nav_sobre_el_creador": "Sobre o Criador",
    "index_hero_title": "InstalaÃ§Ã£o do Windows em NÃ­vel Especialista.",
    "index_hero_subtitle": "BCDeX Ã© a ferramenta de automaÃ§Ã£o avanÃ§ada que **elimina a dependÃªncia de USB ou DVD** para reinstalar o Windows (7-11). Garante um processo de inicializaÃ§Ã£o limpo, seguro e **direto do disco rÃ­gido**.",
    "index_hero_button": "Descubra Como Funciona",
    "index_main_title": "BCDeX: Instale o Windows sem usar USB ou DVD.",
    "index_main_slogan": "Instalar o Windows nunca foi tÃ£o fÃ¡cil!",
    "index_main_description": "A ferramenta que simplifica radicalmente a preparaÃ§Ã£o de instalaÃ§Ãµes do Windows diretamente do seu disco rÃ­gido. EsqueÃ§a as mÃ­dias fÃ­sicas.",
    "index_main_download_button": "Baixar",
    "index_main_tutorial_button": "Ver Guia de Uso",
    "index_features_title": "Principais Recursos do BCDeX",
    "index_feature1_title": "Gerenciamento Seguro de PartiÃ§Ãµes",
    "index_feature1_description": "Utiliza ferramentas nativas do Windows (`diskpart.exe`) para criar uma partiÃ§Ã£o temporÃ¡ria e dedicada, garantindo um espaÃ§o isolado para os arquivos de instalaÃ§Ã£o do sistema operacional.",
    "index_feature2_title": "AutomaÃ§Ã£o de BCD e Scripts",
    "index_feature2_description": "Executa de forma automÃ¡tica e controlada scripts do PowerShell para a montagem de imagens ISO e a configuraÃ§Ã£o precisa dos dados de inicializaÃ§Ã£o (BCD) do sistema.",
    "index_feature3_title": "ExtraÃ§Ã£o e CÃ³pia Otimizadas",
    "index_feature3_description": "Extrai apenas os arquivos essenciais necessÃ¡rios para o inÃ­cio da instalaÃ§Ã£o de sua ISO do Windows (original ou modificada), otimizando o tempo de preparaÃ§Ã£o e o uso do espaÃ§o em disco.",
    "index_security_title": "SeguranÃ§a: Esclarecimento sobre Falsos Positivos",
    "index_security_description": "Devido Ã  manipulaÃ§Ã£o necessÃ¡ria da configuraÃ§Ã£o de inicializaÃ§Ã£o (BCD) e partiÃ§Ãµes, alguns antivÃ­rus podem relatar o BCDeX como um \"falso positivo\". Garantimos que a ferramenta Ã© completamente segura e executa apenas comandos fundamentais do Windows para sua funcionalidade.",
    "donations_supporters_title": "Obrigado aos super CRACKS da Comunidade",
    "donations_supporters_placeholder": "Seu nome pode estar aqui!",
    "donations_supporter_1": "->Descubra como apoiar o BCDeX<-",
    "donations_cta_combo": "Seu nome pode estar aqui. Descubra como",
    "donations_cta_here": "Aqui",
    "footer_creator": "PadeX - Criador de ConteÃºdo e Desenvolvedor",
    "footer_privacy": "Privacidade",
    "footer_terms": "Termos e CondiÃ§Ãµes",
    "footer_copyright": "&copy; 2026 BCDeX. Todos os direitos reservados.",
    "tutorial_page_title": "BCDeX - Tutorial: Guia de Uso",
    "tutorial_hero_title": "BCDeX em AÃ§Ã£o",
    "tutorial_hero_subtitle": "Cansado dos mÃ©todos tradicionais? O BCDeX revoluciona o processo permitindo criar uma unidade de instalaÃ§Ã£o diretamente no seu disco. Assista aos vÃ­deos para ver como Ã© fÃ¡cil e rÃ¡pido.",
    "tutorial_blog_articles_title": "Mais artigos do blog",
    "tutorial_blog_article1_title": "BCDeX 2.3: Modo Turbo",
    "tutorial_blog_article1_description": "Saiba o que o Modo Turbo altera e como reativar recursos.",
    "tutorial_read_more": "Ler mais",
    "tutorial_blog_article2_title": "Otimize o Windows 11 25H2",
    "tutorial_blog_article2_description": "Descubra como remover bloatware durante a instalaÃ§Ã£o.",
    "tutorial_blog_article3_title": "InstalaÃ§Ã£o a partir de PartiÃ§Ã£o",
    "tutorial_blog_article3_description": "EsqueÃ§a o USB. Instale o Windows diretamente do disco rÃ­gido.",
    "tutorial_suggested_videos_title": "VÃ­deos Sugeridos",
    "tutorial_prev_video": "VÃ­deo anterior",
    "tutorial_next_video": "PrÃ³ximo vÃ­deo",
    "tutorial_start_now_button": "Comece a usar o BCDeX agora!",
    "page_title": "BCDeX - O que Ã©?",
    "header_title": "O que Ã© o BCDeX?",
    "header_subtitle": "A ferramenta que revoluciona a sua maneira de instalar o Windows.",
    "section_title_main": "DefiniÃ§Ã£o Expandida",
    "text_definition_1": "O BCDeX Ã© um utilitÃ¡rio de software avanÃ§ado, criado para modernizar e simplificar drasticamente o processo de instalaÃ§Ã£o e reinstalaÃ§Ã£o de sistemas operacionais Windows. Sua principal inovaÃ§Ã£o Ã© eliminar completamente a dependÃªncia de mÃ­dias fÃ­sicas como pen drives ou DVDs, permitindo que todo o processo seja gerenciado diretamente do disco rÃ­gido.",
    "text_definition_2_italic": "Em essÃªncia, o BCDeX funciona como um assistente inteligente que automatiza uma sÃ©rie de tarefas tÃ©cnicas complexas. Isso permite que tanto iniciantes quanto especialistas preparem uma instalaÃ§Ã£o limpa e eficiente do Windows com apenas alguns cliques, reduzindo erros e economizando tempo.",
    "section_title_features": "Funcionalidades Detalhadas",
    "feature_1_title": "Gerenciamento Seguro de PartiÃ§Ãµes",
    "feature_1_desc": "O BCDeX cria uma partiÃ§Ã£o temporÃ¡ria no seu disco de forma nÃ£o destrutiva. Esse espaÃ§o isolado e seguro Ã© onde ficam os arquivos de instalaÃ§Ã£o do Windows, garantindo que seus dados pessoais nÃ£o corram risco.",
    "feature_2_title": "AutomaÃ§Ã£o com PowerShell",
    "feature_2_desc": "A ferramenta usa o poder do PowerShell para montar a ISO, configurar o ambiente de inicializaÃ§Ã£o (BCD) e preparar o sistema para a instalaÃ§Ã£o â€” tudo sem vocÃª precisar escrever uma linha de cÃ³digo.",
    "feature_3_title": "CÃ³pia Inteligente de Arquivos",
    "feature_3_desc": "Em vez de copiar toda a ISO, o BCDeX identifica e extrai apenas os arquivos essenciais para boot e instalaÃ§Ã£o, otimizando tempo e espaÃ§o em disco.",
    "section_title_safety": "Ã‰ seguro usar o BCDeX?",
    "text_safety_1": "Sim, o BCDeX Ã© <strong class=\"text-red-600\">completamente seguro</strong>. Ele foi projetado para interagir com o sistema de forma previsÃ­vel e controlada, usando apenas comandos e ferramentas oficiais do Windows.",
    "text_safety_warning": "Por realizar operaÃ§Ãµes em nÃ­vel de sistema (como modificar partiÃ§Ãµes ou editar o menu de inicializaÃ§Ã£o), alguns antivÃ­rus podem exibir um alerta de \"falso positivo\". Isso Ã© esperado em ferramentas de administraÃ§Ã£o avanÃ§ada. Garantimos que o BCDeX nÃ£o contÃ©m malware e realiza apenas as aÃ§Ãµes necessÃ¡rias e documentadas.",
    "cta_button": "Baixe o BCDeX e simplifique sua vida!",
    "blog_page_title": "Blog do BCDeX",
    "blog_header_title": "Blog do BCDeX",
    "blog_header_subtitle": "Aqui vocÃª encontrarÃ¡ guias detalhados, dicas e as Ãºltimas notÃ­cias sobre o BCDeX e o mundo da instalaÃ§Ã£o de sistemas operacionais.",
    "read_more_link": "Ler mais <svg class=\"w-4 h-4\" data-lucide=\"arrow-right\"></svg>",
    "article_como_descargar_25h2_title": "Como baixar e instalar o Windows 11 25H2",
    "article_como_descargar_25h2_description": "Guia passo a passo + vÃ­deo para baixar, preparar e instalar o 25H2 sem complicaÃ§Ãµes.",
    "article_modo_turbo_title": "BCDeX 2.3: Modo Turbo",
    "article_modo_turbo_description": "Saiba o que muda com o Modo Turbo e como reativar recursos.",
    "article_modo_turbo_v30_title": "BCDeX 3.0 Core: Modo Turbo Reforçado",
    "article_modo_turbo_v30_description": "Veja o que a nova versão otimiza, quais serviços ela altera e como restaurá-los se precisar.",
    "article_win11_25h2_title": "Otimize o Windows 11 25H2",
    "article_win11_25h2_description": "Descubra como remover bloatware durante a instalaÃ§Ã£o.",
    "article_instalacion_particion_title": "InstalaÃ§Ã£o a partir de PartiÃ§Ã£o",
    "article_instalacion_particion_description": "EsqueÃ§a o USB. Instale o Windows diretamente do disco rÃ­gido.",
    "article_uefi_bios_title": "UEFI e BIOS Legacy",
    "article_uefi_bios_description": "DiferenÃ§as, vantagens e desvantagens de cada modo de boot.",
    "article_liberar_espacio_title": "Liberar EspaÃ§o em Disco",
    "article_liberar_espacio_description": "Passos simples para otimizar seu PC e liberar gigabytes de espaÃ§o.",
    "article_archivo_desatendido_title": "Guia de Arquivo Desassistido",
    "article_archivo_desatendido_description": "Aprenda a automatizar a instalaÃ§Ã£o do Windows com um arquivo autounattend.xml.",
    "article_sobre_el_creador_title": "Como nasceu o BCDeX",
    "article_sobre_el_creador_description": "ConheÃ§a como surgiu o BCDeX, seus objetivos e como evoluiu para se tornar uma ferramenta essencial para a instalaÃ§Ã£o do Windows.",
    "article_25h2_page_title": "Como baixar e instalar o Windows 11 25H2 (Guia passo a passo + VÃ­deo)",
    "article_25h2_back_to_all": "â† Voltar para todos os artigos",
    "article_25h2_header_title": "Como baixar e instalar o Windows 11 25H2 (Guia passo a passo + VÃ­deo)",
    "article_25h2_intro": "A Microsoft lanÃ§ou a versÃ£o 25H2 do Windows 11, uma atualizaÃ§Ã£o que muitos desejam instalar do zero para evitar carregar erros, bloatware ou configuraÃ§Ãµes antigas. Neste artigo vocÃª tem o vÃ­deo onde mostro exatamente como baixar, preparar e instalar o Windows 11 25H2 passo a passo, sem complicaÃ§Ãµes.",
    "article_25h2_video_title": "VÃ­deo passo a passo",
    "btn_download_bcdex": "Baixar o BCDeX",
    "article_25h2_what_you_will_see": "O que vocÃª verÃ¡ no tutorial?",
    "article_25h2_li_1": "Como baixar a ISO oficial do Windows 11 25H2",
    "article_25h2_li_2": "Como preparar o USB ou a mÃ­dia de instalaÃ§Ã£o",
    "article_25h2_li_3": "Como iniciar a instalaÃ§Ã£o do zero",
    "article_25h2_li_4": "Quais opÃ§Ãµes escolher para evitar erros comuns",
    "article_25h2_li_5": "Dicas para deixar o Windows limpo e otimizado desde a primeira inicializaÃ§Ã£o",
    "article_25h2_extra_note": "AlÃ©m disso, durante o vÃ­deo explico detalhes importantes para que vocÃª nÃ£o tenha problemas de compatibilidade nem telas pretas, algo comum quando se instala o Windows sem saber o que ajustar.",
    "article_25h2_recommended_download": "Download recomendado",
    "article_25h2_recommended_download_desc": "Para simplificar o processo, recomendo usar o BCDeX: ele prepara tudo automaticamente e evita erros tÃ­picos. Com um clique vocÃª cria a partiÃ§Ã£o temporÃ¡ria, monta a ISO e deixa a instalaÃ§Ã£o pronta.",
    "other_articles_heading": "Outros Artigos do Blog",
    "other_article_win11_25h2": "Windows 11 25H2: Menos Bloatware, Mais Controle",
    "other_article_archivo_desatendido": "BCDeX â€“ Guia de Arquivo Desassistido",
    "other_article_uefi_bios": "UEFI vs BIOS Legacy",
    "other_article_liberar_espacio": "Liberar EspaÃ§o e Otimizar o PC",
    "other_article_instalacion_particion": "Guia: Instalar o Windows a partir de PartiÃ§Ã£o com o BCDeX",
    "other_article_optimizacion_win11": "Guia para Otimizar o Windows 11 na InstalaÃ§Ã£o",
    "article_modo_turbo_back_to_all": "â† Voltar para todos os artigos",
    "page_title_article_1": "BCDeX 2.3: Modo Turbo â€“ O que desativa e como reativar",
    "article_1_title": "ðŸš€ BCDeX 2.3: Modo Turbo â€“ O que desativa e como reativar",
    "article_1_summary": "O Modo Turbo do BCDeX 2.3 Ã© como um botÃ£o mÃ¡gico: ele desliga o que o Windows traz de fÃ¡brica, mas vocÃª quase nunca usa. Assim, seu PC respira e fica mais rÃ¡pido. Se depois sentir falta de algo (impressÃ£o, VPN, scanner), sem problema: aqui mostro como ligar novamente em segundos.",
    "section_1_title": "ðŸ’¡ O que o Modo Turbo faz exatamente?",
    "section_1_intro": "Essa otimizaÃ§Ã£o foca em liberar o mÃ¡ximo de recursos sem comprometer a estabilidade bÃ¡sica do sistema.",
    "turbo_point_1": "Cria um **Ponto de RestauraÃ§Ã£o** antes de qualquer mudanÃ§a (seguranÃ§a em primeiro lugar).",
    "turbo_point_2": "Desliga **serviÃ§os pouco usados** (impressÃ£o, mapas, Xbox, sensores...).",
    "turbo_point_3": "Coloca em **manual** serviÃ§os de rede e atualizaÃ§Ã£o para nÃ£o ficarem consumindo recursos o tempo todo.",
    "turbo_point_4": "Reduz **telemetria** e tarefas agendadas de â€˜experiÃªncia do usuÃ¡rioâ€™.",
    "turbo_point_5": "Ativa o plano de energia de **Desempenho MÃ¡ximo** e desativa a hibernaÃ§Ã£o.",
    "turbo_point_6": "Ajusta **privacidade**: adeus a Recall, Copilot e outros recursos que enviam dados.",
    "section_2_title": "ðŸ”§ Algo que vocÃª precisa foi desativado?",
    "section_2_intro": "Exemplo rÃ¡pido: se a impressora nÃ£o responde porque o serviÃ§o `Spooler` estÃ¡ desligado. SoluÃ§Ã£o: abra o **PowerShell** como administrador e cole o comando de ativaÃ§Ã£o.",
    "section_2_subtitle_1": "ðŸ“‹ Lista de serviÃ§os bÃ¡sicos que o Modo Turbo altera",
    "section_3_title": "ðŸ“‹ Outros serviÃ§os que vocÃª pode encontrar desativados",
    "section_3_intro": "Nem todos aparecem em todas as versÃµes do Windows. Se precisar, ative com o comando abaixo (PowerShell como administrador).",
    "section_4_title": "ðŸ•’ ServiÃ§os em â€˜pausaâ€™ (Manual): iniciam sozinhos quando necessÃ¡rios",
    "section_4_intro": "Esses serviÃ§os ficam como 'Manual', ou seja, o Windows inicia automaticamente apenas quando algum app ou recurso solicita, economizando recursos na inicializaÃ§Ã£o. Se preferir que estejam sempre prontos, force o modo AutomÃ¡tico:",
    "section_5_title": "ðŸ—‘ï¸ DesinstalaÃ§Ã£o de aplicativos e componentes",
    "section_5_intro": "O Modo Turbo tambÃ©m remove alguns apps e componentes prÃ©-instalados considerados â€˜bloatwareâ€™ para deixar o sistema mais leve. Aqui explico o que Ã© removido e como recuperar.",
    "section_5_subtitle_1": "Apps (Clima, Microsoft 365, Teams, To-Do)",
    "section_5_apps_desc": "FunÃ§Ã£o: SÃ£o aplicativos da Microsoft que vÃªm com o Windows. SÃ£o removidos para limpar o menu Iniciar e liberar espaÃ§o.<br>ReativaÃ§Ã£o: Pesquise e instale de graÃ§a pela <a href=\"https://www.microsoft.com/pt-br/store/apps/windows\" target=\"_blank\" class=\"external-link\">Microsoft Store</a>.",
    "section_5_subtitle_2": "Microsoft Edge e seu Bloqueio de ReinstalaÃ§Ã£o",
    "section_5_edge_desc": "FunÃ§Ã£o: O Edge Ã© removido caso vocÃª prefira outro navegador e nÃ£o queira que ele consuma recursos.<br>Reativar Edge: baixe o instalador na <a href=\"https://www.microsoft.com/pt-br/edge\" target=\"_blank\" class=\"external-link\">pÃ¡gina oficial do Microsoft Edge</a>.",
    "section_5_edge_block_desc": "Bloqueio de ReinstalaÃ§Ã£o: O Modo Turbo ativa um bloqueio no Registro para evitar que o Windows Update reinstale o Edge. Para desativar e permitir as atualizaÃ§Ãµes, execute o comando abaixo no PowerShell como administrador:",
    "important_note_title": "ðŸš¨ Importante: Variabilidade no Windows!",
    "important_note_content": "Nem todos os serviÃ§os existem em todas as versÃµes do Windows. O Windows 7, 10 e 11 nÃ£o possuem exatamente os mesmos recursos, e tambÃ©m mudam entre ediÃ§Ãµes (Home, Pro, Enterprise) e entre builds/atualizaÃ§Ãµes. **Se vocÃª executar um comando e aparecer erro dizendo que o serviÃ§o nÃ£o existe, tudo bem:** ele simplesmente nÃ£o estÃ¡ presente no seu Windows. **Dica:** reative apenas o que realmente precisar."
,
    "article_win11_25h2_back_to_all": "â† Voltar para todos os artigos",

    "section_win11_25h2_1_p1": "A principal novidade chega via Editor de PolÃ­tica de Grupo. Se vocÃª usa Windows 11 Pro, pressione Win + R, digite gpedit.msc e tecle Enter.",
    "section_win11_25h2_1_p2": "No Editor de PolÃ­tica de Grupo:",
    "section_win11_25h2_1_li1": "VÃ¡ em <span class=\"font-semibold\">ConfiguraÃ§Ã£o do Computador â†’ Modelos Administrativos â†’ Componentes do Windows</span>.",
    "section_win11_25h2_1_li2": "Encontre a nova opÃ§Ã£o chamada <span class=\"font-semibold\">Remover aplicativos prÃ©-instalados</span>.",
    "section_win11_25h2_1_li3": "Clique duas vezes nela.",
    "section_win11_25h2_1_li4": "Selecione <span class=\"font-semibold\">Habilitado</span>.",
    "section_win11_25h2_1_li5": "Salve as alteraÃ§Ãµes.",
    "section_win11_25h2_1_li6": "Reinicie o PC. Pronto! Agora vocÃª pode desinstalar apps como Paint, Media Player, Cortana, Sticky Notes etc. diretamente nas ConfiguraÃ§Ãµes.",
    "section_win11_25h2_1_p3": "Se vocÃª usa Windows 11 Home, o Editor de PolÃ­tica de Grupo nÃ£o estÃ¡ disponÃ­vel oficialmente. HÃ¡ mÃ©todos nÃ£o suportados para habilitÃ¡-lo ou editar o registro, mas nÃ£o sÃ£o recomendados para iniciantes.",

    "section_win11_25h2_2_p1": "O processo Ã© simples para usuÃ¡rios do Windows 11 Pro. Basta usar o Editor de PolÃ­tica de Grupo e habilitar a opÃ§Ã£o para remover aplicativos prÃ©-instalados.",
    "section_win11_25h2_2_p2": "<span class=\"font-semibold\">ConfiguraÃ§Ã£o do Computador > Componentes do Windows > ImplantaÃ§Ã£o de Pacotes de Aplicativos</span>",
    "section_win11_25h2_2_p3": "Para usuÃ¡rios do Windows 11 Home, ainda nÃ£o hÃ¡ soluÃ§Ã£o oficial. Recomenda-se aguardar atualizaÃ§Ãµes futuras ou usar mÃ©todos alternativos com cautela.",
    "section_win11_25h2_2_p4": "<span class=\"font-semibold\">Nota:</span> A disponibilidade desta opÃ§Ã£o pode variar conforme sua compilaÃ§Ã£o do Windows 11. Certifique-se de estar atualizado.",
    "section_win11_25h2_2_p5": "ApÃ³s habilitar a polÃ­tica, acesse <span class=\"font-semibold\">ConfiguraÃ§Ãµes â†’ Aplicativos â†’ Aplicativos instalados</span> e remova os que desejar.",
    "section_win11_25h2_2_p6": "Lembre-se: nem todos os apps podem ser removidos, mas a lista serÃ¡ maior do que nunca.",

    "important_win11_25h2_li1": "Nem todos os aplicativos podem ser desinstalados. Alguns componentes essenciais do sistema permanecerÃ£o protegidos.",
    "important_win11_25h2_li2": "Aplicativos como Paint, Media Player, Cortana, Sticky Notes e outros podem ser removidos. Apps do sistema como Explorador de Arquivos, Microsoft Store ou ConfiguraÃ§Ãµes permanecerÃ£o protegidos.",
    "important_win11_25h2_li3": "A disponibilidade pode variar conforme a compilaÃ§Ã£o e a regiÃ£o.",
    "important_win11_25h2_li4": "Sempre faÃ§a backup antes de remover aplicativos importantes.",

    "section_win11_25h2_3_p1": "O novo recurso Ã© esperado na atualizaÃ§Ã£o do Windows 11 25H2, prevista para o fim de 2026. UsuÃ¡rios do programa Insider podem recebÃª-lo antes.",
    "section_win11_25h2_4_li1": "Menos bloatware significa um sistema mais limpo, rÃ¡pido e com mais espaÃ§o livre.",
    "section_win11_25h2_4_li2": "Oferece ao usuÃ¡rio mais controle sobre o que permanece instalado no PC.",
    "section_win11_25h2_5_li1": "AlÃ©m dos aplicativos mencionados, outros podem se tornar removÃ­veis no futuro conforme o Windows evolui.",
    "section_win11_25h2_5_li2": "A lista de apps removÃ­veis pode crescer em futuras atualizaÃ§Ãµes.",
    "section_win11_25h2_5_li3": "Ferramentas de terceiros ainda podem ser Ãºteis para remoÃ§Ãµes avanÃ§adas.",
    "section_win11_25h2_5_li4": "A Microsoft pode reverter ou mudar essa polÃ­tica em compilaÃ§Ãµes futuras.",
    "section_win11_25h2_5_p1": "Fique atento Ã s notÃ­cias e sempre leia as notas de versÃ£o antes de atualizar.",
    "conclusion_win11_25h2_p1": "A atualizaÃ§Ã£o do Windows 11 25H2 marca um passo importante no controle do usuÃ¡rio sobre o sistema.",
    "conclusion_win11_25h2_p2": "Remover bloatware nunca foi tÃ£o fÃ¡cil â€” e oficial! Aproveite para deixar o Windows com a sua cara.",

    "donations_page_title": "BCDeX: Como a ideia nasceu e quem estÃ¡ por trÃ¡s do projeto",
    "donations_title": "Torne-se um Parceiro do Projeto",
    "donations_intro": "O BCDeX Ã© gratuito e sempre serÃ¡ graÃ§as ao apoio de uma comunidade incrÃ­vel. Sua contribuiÃ§Ã£o nÃ£o Ã© apenas uma doaÃ§Ã£o: Ã© um 'soquinho' no projeto que jÃ¡ te poupou de pagar um tÃ©cnico, perder horas ou comprar ferramentas extras. Ã‰ investir para que esta ferramenta â€”feita por um entusiasta para entusiastasâ€” continue existindo e melhorando.",
    "donations_why_title": "Por que seu apoio Ã© tÃ£o importante?",
    "donations_why_item1_title": "ðŸš€ Impulsiona novos recursos",
    "donations_why_item1_text": "Sempre que a Microsoft muda algo, Ã© preciso reescrever partes do cÃ³digo do zero. Seu apoio permite dedicar tempo a essas atualizaÃ§Ãµes e desenvolver o que a comunidade pede: mais compatibilidade, mais automaÃ§Ã£o, mais personalizaÃ§Ã£o.",
    "donations_why_item2_title": "ðŸ›¡ï¸ Garante a continuidade do projeto",
    "donations_why_item2_text": "Servidores, domÃ­nios, ferramentas de desenvolvimento e testes nÃ£o sÃ£o grÃ¡tis. Sem apoio, o projeto termina como 90% do software Ãºtil que morre por falta de suporte. Se a comunidade apoia, o BCDeX continua gratuito, limpo e sem patrocinadores ou spyware.",
    "donations_why_item3_title": "â˜• Alimenta a paixÃ£o (e o desenvolvedor)",
    "donations_why_item3_text": "Este Ã© um projeto de um Ãºnico desenvolvedor. Cada doaÃ§Ã£o literalmente vira cafÃ©, horas de cÃ³digo, correÃ§Ã£o de bugs e suporte aos usuÃ¡rios. Ã‰ uma forma de dizer â€˜vocÃª me ajudou â€” aqui vai meu soquinho na vida realâ€™.", 
    "donations_why_footer": "Se o BCDeX te ajudou, retribua. Se nÃ£o, ao menos nÃ£o deixe que desapareÃ§a por falta de apoio.",
    "donations_how_title": "Seu Apoio Sustenta o BCDeX: Toda ContribuiÃ§Ã£o Conta!",
    "donations_how_text": "O BCDeX continua crescendo graÃ§as a vocÃª. Sua doaÃ§Ã£o â€”de qualquer valorâ€” Ã© vital para financiar a manutenÃ§Ã£o, garantir servidores estÃ¡veis e acelerar o desenvolvimento de novos recursos. Ajude-nos a seguir em frente! Obrigado por ser um pilar da nossa comunidade.",

    "article_instalacion_particion_back_to_all": "â† Voltar para todos os artigos",
    "section_instalacion_particion_process_title": "O processo com o BCDeX: FÃ¡cil e RÃ¡pido",
    "section_instalacion_particion_process_p1": "Instalar o Windows a partir de uma partiÃ§Ã£o do disco Ã© um mÃ©todo extremamente eficiente que o BCDeX automatiza por completo. O processo comeÃ§a escolhendo o disco onde serÃ¡ criada uma partiÃ§Ã£o temporÃ¡ria e a imagem ISO do Windows que vocÃª deseja instalar. O BCDeX Ã© compatÃ­vel com vÃ¡rias versÃµes, do Windows 7 ao 11, inclusive ISOs modificadas. Uma grande vantagem Ã© ignorar automaticamente as verificaÃ§Ãµes de TPM e Secure Boot, facilitando a instalaÃ§Ã£o do Windows 11 em hardware nÃ£o compatÃ­vel.",
    "section_instalacion_particion_process_p2": "Ao clicar em \"AvanÃ§ar\", o app cuida de tudo: cria a partiÃ§Ã£o, monta a ISO e copia os arquivos de instalaÃ§Ã£o. O processo Ã© totalmente desassistido atÃ© o prÃ³ximo passo.",
    "section_instalacion_particion_custom_title": "PersonalizaÃ§Ã£o e OtimizaÃ§Ã£o (Opcional)",
    "section_instalacion_particion_custom_p1": "Antes de reiniciar, o BCDeX oferece um de seus recursos mais poderosos: a personalizaÃ§Ã£o da instalaÃ§Ã£o. VocÃª pode criar um usuÃ¡rio local, pular a configuraÃ§Ã£o de rede durante o OOBE, reduzir telemetria e desinstalar bloatware. Assim vocÃª tem um sistema mais limpo, rÃ¡pido e privado desde a primeira inicializaÃ§Ã£o.",
    "section_instalacion_particion_install_cleanup_title": "InstalaÃ§Ã£o e Limpeza Final",
    "section_instalacion_particion_install_p1": "Com tudo pronto, o aplicativo pedirÃ¡ para reiniciar. Ao fazer isso, o sistema iniciarÃ¡ automaticamente no ambiente de instalaÃ§Ã£o do Windows preparado pelo BCDeX. Se nÃ£o iniciar, selecione a entrada \"BCDeX Boot\" no menu de boot do seu PC.",
    "important_note_instalacion_particion_title": "ðŸ’¡ Importante:",
    "important_note_instalacion_particion_p1": "Durante a instalaÃ§Ã£o do Windows, vocÃª verÃ¡ uma partiÃ§Ã£o chamada <strong>\"BCDeX Vol\"</strong>. Ã‰ crucial que <strong>nÃ£o a exclua</strong>, pois ela contÃ©m todos os arquivos necessÃ¡rios para concluir a instalaÃ§Ã£o.",
    "section_instalacion_particion_cleanup_p1": "Quando o novo Windows estiver funcionando, o Ãºltimo passo Ã© a limpeza. Execute o BCDeX novamente (na partiÃ§Ã£o temporÃ¡ria) e escolha \"Desfazer alteraÃ§Ãµes\". Isso removerÃ¡ a partiÃ§Ã£o de instalaÃ§Ã£o, liberando espaÃ§o e deixando o sistema impecÃ¡vel.",
    "page_title_article_sobre_el_creador": "BCDeX: Como a ideia nasceu e quem estÃ¡ por trÃ¡s do projeto",
    "article_sobre_el_creador_back_link": "â† Voltar para todos os artigos",
    "article_sobre_el_creador_summary": "OlÃ¡, eu sou o JosÃ© 'PadeX' ðŸ‘‹ e se vocÃª estÃ¡ lendo isso, provavelmente jÃ¡ conhece meu aplicativo BCDeX, ou pelo menos parece familiar. Neste post, quero contar um pouco da histÃ³ria por trÃ¡s do projeto. Porque sim, embora possa parecer um aplicativo mÃ¡gico que aparece na sua Ã¡rea de trabalho e cria uma partiÃ§Ã£o inicializÃ¡vel como por mÃ¡gica... por trÃ¡s hÃ¡ muitas noites sem dormir, testes fracassados e litros de cafÃ© â˜•.",
    "section_sobre_el_creador_1_title": "Tudo comeÃ§ou por causa dos 'WeSeBes'... e um script",
    "section_sobre_el_creador_1_p1": "Tudo comeÃ§ou quando um dia, depois de instalar o Windows pela enÃ©sima vez em diferentes PCs (alguns sem portas USB funcionais, outros com BIOS que nÃ£o aceitam inicializaÃ§Ã£o por USB, outros com UEFI super restritivos...), eu disse a mim mesmo:",
    "section_sobre_el_creador_1_quote1": "â€œPor que isso tem que ser tÃ£o complicado? E se eu criar uma maneira de instalar o Windows <br>do mesmo disco rÃ­gido, sem pendrives, sem DVDs e sem tanto trabalho?â€",
    "section_sobre_el_creador_1_p2": "Foi assim que comecei criando um pequeno script em PowerShell que simplesmente criava uma partiÃ§Ã£o secundÃ¡ria no disco para atuar como um â€œlanÃ§adorâ€ para a instalaÃ§Ã£o do Windows. Parecia uma boa ideia, atÃ© que percebi algo: era preciso montar a ISO manualmente, copiar os arquivos um por um... e isso para muitos usuÃ¡rios era uma dor de cabeÃ§a.",
    "section_sobre_el_creador_1_p3": "AÃ­ me lembrei de uma frase que um professor me repetia nos meus anos de estudo:",
    "section_sobre_el_creador_1_quote2": "â€œVocÃªs devem aprender a programar para leigos.â€",
    "section_sobre_el_creador_1_p4": "E ele nÃ£o dizia isso de forma ofensiva. O que ele queria dizer era que, ao desenvolver algo, Ã© preciso pensar absolutamente tudo do ponto de vista do usuÃ¡rio final, inclusive daquele que nÃ£o tem a menor ideia de informÃ¡tica. A experiÃªncia tem que ser tÃ£o simples que qualquer um possa fazÃª-lo sem ler um manual.",
    "section_sobre_el_creador_1_p5": "Essa frase me marcou. E eu me propus: â€œComo posso fazer para que o usuÃ¡rio nem precise montar a ISO?â€",
    "section_sobre_el_creador_2_title": "Aprendendo na marra (e com o Google)",
    "section_sobre_el_creador_2_p1": "Foi assim que comecei a trabalhar na automaÃ§Ã£o da cÃ³pia da ISO diretamente do PowerShell. Sem necessidade de montÃ¡-la, sem passos estranhos. Spoiler: nÃ£o foi fÃ¡cil. Tive que ler bastante sobre estruturas de arquivos ISO, WIMs, extrair conteÃºdo diretamente sem unidades virtuaisâ€¦ mas no final consegui que tudo fosse feito automaticamente.",
    "section_sobre_el_creador_2_p2": "AtÃ© aÃ­ tudo bem. Mas me deparei com outro problema: o console do PowerShell nÃ£o Ã© exatamente o mais amigÃ¡vel para muitos usuÃ¡rios. Intimida, dÃ¡ erros em vermelho, e nÃ£o Ã© tÃ£o claro o que fazer se algo falhar.",
    "section_sobre_el_creador_2_p3": "EntÃ£o decidi dar o prÃ³ximo passo: criar uma interface grÃ¡fica simples, mas funcional, que guiasse o usuÃ¡rio em todo o processo â€”desde a criaÃ§Ã£o da partiÃ§Ã£o atÃ© a cÃ³pia da ISO e a configuraÃ§Ã£o da inicializaÃ§Ã£o.",
    "section_sobre_el_creador_2_p4": "AÃ­ nasceu o que hoje Ã© o <strong>BCDeX</strong>.",
    "section_sobre_el_creador_3_title": "E de onde vem o nome \"BCDeX\"?",
    "section_sobre_el_creador_3_p1": "Quando o aplicativo comeÃ§ou a tomar forma, eu precisava de um nome. Algo que refletisse o que ele fazia, mas que tambÃ©m tivesse um pouco de identidade pessoal.",
    "section_sobre_el_creador_3_p2": "Foi aÃ­ que me ocorreu combinar duas coisas: BCD, pelo famoso Boot Configuration Data que o aplicativo manipula para criar as entradas de inicializaÃ§Ã£o do Windows... e PadeX, que Ã© o nome do meu canal no YouTube, onde compartilho muitos desses projetos.",
    "section_sobre_el_creador_3_p3": "Assim nasceu o nome BCDeX: uma fusÃ£o do tÃ©cnico e do pessoal. ðŸ˜„",
    "section_sobre_el_creador_4_title": "E quem estÃ¡ por trÃ¡s?",
    "section_sobre_el_creador_4_p1": "Como eu disse antes, eu sou o PadeX, e sim, eu faÃ§o de tudo: programador, designer, testador, criador de conteÃºdo e atÃ© suporte tÃ©cnico nos comentÃ¡rios dos meus vÃ­deos ðŸ˜….",
    "section_sobre_el_creador_4_p2": "Tudo o que vocÃª vÃª neste site, no canal do YouTube e no aplicativo, sou eu quem faÃ§o (por enquanto). Com erros, com melhorias contÃ­nuas e com muita vontade de continuar avanÃ§ando.",
    "section_sobre_el_creador_4_p3": "O BCDeX nÃ£o Ã© apenas uma ferramenta. Ã‰ o resultado de muitos testes, fracassos, aprendizados e, acima de tudo, de uma obsessÃ£o por facilitar a vida de quem quer instalar o Windows sem complicaÃ§Ãµes.",
    "section_sobre_el_creador_5_title": "O que vem a seguir?",
    "section_sobre_el_creador_5_p1": "Continuar melhorando. Quero integrar novas funÃ§Ãµes, como otimizaÃ§Ãµes pÃ³s-instalaÃ§Ã£o, mais compatibilidade e uma ou outra surpresa pensada para deixar seu Windows pronto e afinado desde o primeiro inÃ­cio.",
    "section_sobre_el_creador_5_p2": "Ã‰ por isso que o apoio e as contribuiÃ§Ãµes de quem usa o aplicativo tambÃ©m sÃ£o tÃ£o importantes. GraÃ§as a isso, posso continuar mantendo o site, atualizando a ferramenta e dedicando tempo para melhorÃ¡-la constantemente.",
    "section_sobre_el_creador_5_p3": "E se vocÃª tiver interesse em saber mais ou dar ideias, convido vocÃª a me seguir nas redes sociais, no <a href=\"https://www.youtube.com/@PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">YouTube</a>, <a href=\"https://www.instagram.com/padexchn/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Instagram</a>, <a href=\"https://www.tiktok.com/@padexch\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">TikTok</a>, <a href=\"https://x.com/PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">X</a>, <a href=\"https://www.facebook.com/PadeXch/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Facebook</a> e deixar um comentÃ¡rio por lÃ¡.",
    "section_sobre_el_creador_5_p4": "Obrigado por fazer parte disso. ðŸ’™",
    "section_sobre_el_creador_5_p5": "â€” <strong>PadeX</strong> ðŸ’»",
    "download_page_title": "BCDeX - Download",
    "download_header_title": "Baixar BCDeX",
    "download_header_subtitle": "VocÃª estÃ¡ a um clique de simplificar suas instalaÃ§Ãµes do Windows para sempre.",
    "download_v23_title": "VersÃ£o 2.3",
    "download_updated_on_label": "Atualizado em:",
    "download_features_title": "Principais CaracterÃ­sticas",
    "download_v23_b1": "CompatÃ­vel com <strong>Windows 7</strong>, <strong>8</strong>, <strong>8.1</strong>, <strong>10</strong> e <strong>11</strong>",
    "download_v23_b2": "CriaÃ§Ã£o de unidades <strong>USB inicializÃ¡veis</strong>",
    "download_v23_b3": "<strong>Modo Turbo</strong>: Desativa serviÃ§os raramente usados para liberar recursos do sistema",
    "download_v23_b4": "Suporte para inicializaÃ§Ã£o <strong>UEFI</strong> e <strong>Legacy</strong>",
    "download_v23_b5": "<strong>100% seguro e livre de malware</strong>",
    "download_links_title": "Links para Download",
    "download_server_1": "â¬‡ï¸ Servidor #1",
    "download_server_2": "â¬‡ï¸ Servidor #2",
    "download_server_3": "â¬‡ï¸ Servidor #3",
    "download_changes_title": "MudanÃ§as nesta versÃ£o",
    "download_changes_text": "Melhorias de desempenho e estabilidade foram implementadas.",
    "download_win7_compat_title": "Compatibilidade com Windows 7",
    "download_win7_compat_desc": "Pacote .rar com instaladores do .NET Framework 4.0 e atualizaÃ§Ãµes cumulativas x86/x64 necessÃ¡rias para executar o BCDeX no Windows 7.",
    "download_win7_package_btn": "Baixar pacote do Windows 7",
    "download_v13_title": "VersÃ£o 1.3",
    "download_v13_b1": "CompatÃ­vel com Windows 8, 10 e 11",
    "download_v13_b2": "Suporte para inicializaÃ§Ã£o UEFI e Legacy",
    "download_v13_b3": "100% seguro e livre de malware",
    "download_warning_title": "Aviso Importante",
    "download_warning_text": "O BCDeX Ã© uma ferramenta destinada a usuÃ¡rios com alguma experiÃªncia. Embora tenhamos projetado o aplicativo com muito cuidado, o uso incorreto pode afetar o sistema. Recomendamos seguir as instruÃ§Ãµes e usÃ¡-lo com critÃ©rio. Para mais informaÃ§Ãµes, consulte nossos <a href=\"terminos.html\" class=\"text-red-600 hover:underline\">Termos e CondiÃ§Ãµes</a>.",
    "download_contact_text": "Se vocÃª tiver problemas com o download ou alguma sugestÃ£o, nÃ£o hesite em <a href=\"contacto.html\" class=\"text-red-600 hover:underline\">nos contatar</a>.",

    "contact_page_title": "Contato",
    "contact_title": "Contato",
    "contact_intro": "Tem dÃºvidas, sugestÃµes ou precisa de suporte?",
    "contact_intro_secondary": "Estas sÃ£o as melhores formas de falar com a gente:",
    "contact_youtube": "YouTube",
    "contact_facebook": "Facebook",
    "contact_discord": "Discord",
    "contact_email": "Email",
    "contact_tiktok": "TikTok",
    "contact_instagram": "Instagram",
    "contact_x": "X",
    "contact_support_title": "Apoie o projeto",
    "contact_support_text": "Toda contribuiÃ§Ã£o, grande ou pequena, ajuda a continuar melhorando o BCDeX para toda a comunidade.",
    "contact_support_button": "Ver opÃ§Ãµes de doaÃ§Ã£o"
}
