const translations_pt_br = {
    "page_title_index": "BCDeX - Instalação do Windows sem USB",
    "nav_home": "Início",
    "nav_tutorial": "Tutorial",
    "nav_what_is": "O que é BCDeX?",
    "nav_blog": "Blog",
    "nav_donations": "Doações",
    "nav_download": "Download",
    "nav_contact": "Contato",
    "nav_sobre_el_creador": "Sobre o Criador",
    "index_hero_title": "Instalação do Windows em Nível Especialista.",
    "index_hero_subtitle": "BCDeX é a ferramenta de automação avançada que **elimina a dependência de USB ou DVD** para reinstalar o Windows (7-11). Garante um processo de inicialização limpo, seguro e **direto do disco rígido**.",
    "index_hero_button": "Descubra Como Funciona",
    "index_main_title": "BCDeX: Instale o Windows sem usar USB ou DVD.",
    "index_main_slogan": "Instalar o Windows nunca foi tão fácil!",
    "index_main_description": "A ferramenta que simplifica radicalmente a preparação de instalações do Windows diretamente do seu disco rígido. Esqueça as mídias físicas.",
    "index_main_download_button": "Baixar",
    "index_main_tutorial_button": "Ver Guia de Uso",
    "index_features_title": "Principais Recursos do BCDeX",
    "index_feature1_title": "Gerenciamento Seguro de Partições",
    "index_feature1_description": "Utiliza ferramentas nativas do Windows (`diskpart.exe`) para criar uma partição temporária e dedicada, garantindo um espaço isolado para os arquivos de instalação do sistema operacional.",
    "index_feature2_title": "Automação de BCD e Scripts",
    "index_feature2_description": "Executa de forma automática e controlada scripts do PowerShell para a montagem de imagens ISO e a configuração precisa dos dados de inicialização (BCD) do sistema.",
    "index_feature3_title": "Extração e Cópia Otimizadas",
    "index_feature3_description": "Extrai apenas os arquivos essenciais necessários para o início da instalação de sua ISO do Windows (original ou modificada), otimizando o tempo de preparação e o uso do espaço em disco.",
    "index_security_title": "Segurança: Esclarecimento sobre Falsos Positivos",
    "index_security_description": "Devido à manipulação necessária da configuração de inicialização (BCD) e partições, alguns antivírus podem relatar o BCDeX como um \"falso positivo\". Garantimos que a ferramenta é completamente segura e executa apenas comandos fundamentais do Windows para sua funcionalidade.",
    "donations_supporters_title": "Obrigado aos super CRACKS da Comunidade",
    "donations_supporters_placeholder": "Seu nome pode estar aqui!",
    "donations_supporter_1": "->Descubra como apoiar o BCDeX<-",
    "footer_creator": "PadeX - Criador de Conteúdo e Desenvolvedor",
    "footer_privacy": "Privacidade",
    "footer_terms": "Termos e Condições",
    "footer_copyright": "&copy; 2025 BCDeX. Todos os direitos reservados.",
    "tutorial_page_title": "BCDeX - Tutorial: Guia de Uso",
    "tutorial_hero_title": "BCDeX em Ação",
    "tutorial_hero_subtitle": "Cansado dos métodos tradicionais? O BCDeX revoluciona o processo permitindo criar uma unidade de instalação diretamente no seu disco. Assista aos vídeos para ver como é fácil e rápido.",
    "tutorial_blog_articles_title": "Mais artigos do blog",
    "tutorial_blog_article1_title": "BCDeX 2.3: Modo Turbo",
    "tutorial_blog_article1_description": "Saiba o que o Modo Turbo altera e como reativar recursos.",
    "tutorial_read_more": "Ler mais",
    "tutorial_blog_article2_title": "Otimize o Windows 11 25H2",
    "tutorial_blog_article2_description": "Descubra como remover bloatware durante a instalação.",
    "tutorial_blog_article3_title": "Instalação a partir de Partição",
    "tutorial_blog_article3_description": "Esqueça o USB. Instale o Windows diretamente do disco rígido.",
    "tutorial_suggested_videos_title": "Vídeos Sugeridos",
    "tutorial_prev_video": "Vídeo anterior",
    "tutorial_next_video": "Próximo vídeo",
    "tutorial_start_now_button": "Comece a usar o BCDeX agora!",
    "page_title": "BCDeX - O que é?",
    "header_title": "O que é o BCDeX?",
    "header_subtitle": "A ferramenta que revoluciona a sua maneira de instalar o Windows.",
    "section_title_main": "Definição Expandida",
    "text_definition_1": "O BCDeX é um utilitário de software avançado, criado para modernizar e simplificar drasticamente o processo de instalação e reinstalação de sistemas operacionais Windows. Sua principal inovação é eliminar completamente a dependência de mídias físicas como pen drives ou DVDs, permitindo que todo o processo seja gerenciado diretamente do disco rígido.",
    "text_definition_2_italic": "Em essência, o BCDeX funciona como um assistente inteligente que automatiza uma série de tarefas técnicas complexas. Isso permite que tanto iniciantes quanto especialistas preparem uma instalação limpa e eficiente do Windows com apenas alguns cliques, reduzindo erros e economizando tempo.",
    "section_title_features": "Funcionalidades Detalhadas",
    "feature_1_title": "Gerenciamento Seguro de Partições",
    "feature_1_desc": "O BCDeX cria uma partição temporária no seu disco de forma não destrutiva. Esse espaço isolado e seguro é onde ficam os arquivos de instalação do Windows, garantindo que seus dados pessoais não corram risco.",
    "feature_2_title": "Automação com PowerShell",
    "feature_2_desc": "A ferramenta usa o poder do PowerShell para montar a ISO, configurar o ambiente de inicialização (BCD) e preparar o sistema para a instalação — tudo sem você precisar escrever uma linha de código.",
    "feature_3_title": "Cópia Inteligente de Arquivos",
    "feature_3_desc": "Em vez de copiar toda a ISO, o BCDeX identifica e extrai apenas os arquivos essenciais para boot e instalação, otimizando tempo e espaço em disco.",
    "section_title_safety": "É seguro usar o BCDeX?",
    "text_safety_1": "Sim, o BCDeX é <strong class=\"text-red-600\">completamente seguro</strong>. Ele foi projetado para interagir com o sistema de forma previsível e controlada, usando apenas comandos e ferramentas oficiais do Windows.",
    "text_safety_warning": "Por realizar operações em nível de sistema (como modificar partições ou editar o menu de inicialização), alguns antivírus podem exibir um alerta de \"falso positivo\". Isso é esperado em ferramentas de administração avançada. Garantimos que o BCDeX não contém malware e realiza apenas as ações necessárias e documentadas.",
    "cta_button": "Baixe o BCDeX e simplifique sua vida!",
    "blog_page_title": "Blog do BCDeX",
    "blog_header_title": "Blog do BCDeX",
    "blog_header_subtitle": "Aqui você encontrará guias detalhados, dicas e as últimas notícias sobre o BCDeX e o mundo da instalação de sistemas operacionais.",
    "read_more_link": "Ler mais <svg class=\"w-4 h-4\" data-lucide=\"arrow-right\"></svg>",
    "article_como_descargar_25h2_title": "Como baixar e instalar o Windows 11 25H2",
    "article_como_descargar_25h2_description": "Guia passo a passo + vídeo para baixar, preparar e instalar o 25H2 sem complicações.",
    "article_modo_turbo_title": "BCDeX 2.3: Modo Turbo",
    "article_modo_turbo_description": "Saiba o que muda com o Modo Turbo e como reativar recursos.",
    "article_win11_25h2_title": "Otimize o Windows 11 25H2",
    "article_win11_25h2_description": "Descubra como remover bloatware durante a instalação.",
    "article_instalacion_particion_title": "Instalação a partir de Partição",
    "article_instalacion_particion_description": "Esqueça o USB. Instale o Windows diretamente do disco rígido.",
    "article_uefi_bios_title": "UEFI e BIOS Legacy",
    "article_uefi_bios_description": "Diferenças, vantagens e desvantagens de cada modo de boot.",
    "article_liberar_espacio_title": "Liberar Espaço em Disco",
    "article_liberar_espacio_description": "Passos simples para otimizar seu PC e liberar gigabytes de espaço.",
    "article_archivo_desatendido_title": "Guia de Arquivo Desassistido",
    "article_archivo_desatendido_description": "Aprenda a automatizar a instalação do Windows com um arquivo autounattend.xml.",
    "article_sobre_el_creador_title": "Como nasceu o BCDeX",
    "article_sobre_el_creador_description": "Conheça como surgiu o BCDeX, seus objetivos e como evoluiu para se tornar uma ferramenta essencial para a instalação do Windows.",
    "article_25h2_page_title": "Como baixar e instalar o Windows 11 25H2 (Guia passo a passo + Vídeo)",
    "article_25h2_back_to_all": "← Voltar para todos os artigos",
    "article_25h2_header_title": "Como baixar e instalar o Windows 11 25H2 (Guia passo a passo + Vídeo)",
    "article_25h2_intro": "A Microsoft lançou a versão 25H2 do Windows 11, uma atualização que muitos desejam instalar do zero para evitar carregar erros, bloatware ou configurações antigas. Neste artigo você tem o vídeo onde mostro exatamente como baixar, preparar e instalar o Windows 11 25H2 passo a passo, sem complicações.",
    "article_25h2_video_title": "Vídeo passo a passo",
    "btn_download_bcdex": "Baixar o BCDeX",
    "article_25h2_what_you_will_see": "O que você verá no tutorial?",
    "article_25h2_li_1": "Como baixar a ISO oficial do Windows 11 25H2",
    "article_25h2_li_2": "Como preparar o USB ou a mídia de instalação",
    "article_25h2_li_3": "Como iniciar a instalação do zero",
    "article_25h2_li_4": "Quais opções escolher para evitar erros comuns",
    "article_25h2_li_5": "Dicas para deixar o Windows limpo e otimizado desde a primeira inicialização",
    "article_25h2_extra_note": "Além disso, durante o vídeo explico detalhes importantes para que você não tenha problemas de compatibilidade nem telas pretas, algo comum quando se instala o Windows sem saber o que ajustar.",
    "article_25h2_recommended_download": "Download recomendado",
    "article_25h2_recommended_download_desc": "Para simplificar o processo, recomendo usar o BCDeX: ele prepara tudo automaticamente e evita erros típicos. Com um clique você cria a partição temporária, monta a ISO e deixa a instalação pronta.",
    "other_articles_heading": "Outros Artigos do Blog",
    "other_article_win11_25h2": "Windows 11 25H2: Menos Bloatware, Mais Controle",
    "other_article_archivo_desatendido": "BCDeX – Guia de Arquivo Desassistido",
    "other_article_uefi_bios": "UEFI vs BIOS Legacy",
    "other_article_liberar_espacio": "Liberar Espaço e Otimizar o PC",
    "other_article_instalacion_particion": "Guia: Instalar o Windows a partir de Partição com o BCDeX",
    "other_article_optimizacion_win11": "Guia para Otimizar o Windows 11 na Instalação",
    "article_modo_turbo_back_to_all": "← Voltar para todos os artigos",
    "page_title_article_1": "BCDeX 2.3: Modo Turbo – O que desativa e como reativar",
    "article_1_title": "🚀 BCDeX 2.3: Modo Turbo – O que desativa e como reativar",
    "article_1_summary": "O Modo Turbo do BCDeX 2.3 é como um botão mágico: ele desliga o que o Windows traz de fábrica, mas você quase nunca usa. Assim, seu PC respira e fica mais rápido. Se depois sentir falta de algo (impressão, VPN, scanner), sem problema: aqui mostro como ligar novamente em segundos.",
    "section_1_title": "💡 O que o Modo Turbo faz exatamente?",
    "section_1_intro": "Essa otimização foca em liberar o máximo de recursos sem comprometer a estabilidade básica do sistema.",
    "turbo_point_1": "Cria um **Ponto de Restauração** antes de qualquer mudança (segurança em primeiro lugar).",
    "turbo_point_2": "Desliga **serviços pouco usados** (impressão, mapas, Xbox, sensores...).",
    "turbo_point_3": "Coloca em **manual** serviços de rede e atualização para não ficarem consumindo recursos o tempo todo.",
    "turbo_point_4": "Reduz **telemetria** e tarefas agendadas de ‘experiência do usuário’.",
    "turbo_point_5": "Ativa o plano de energia de **Desempenho Máximo** e desativa a hibernação.",
    "turbo_point_6": "Ajusta **privacidade**: adeus a Recall, Copilot e outros recursos que enviam dados.",
    "section_2_title": "🔧 Algo que você precisa foi desativado?",
    "section_2_intro": "Exemplo rápido: se a impressora não responde porque o serviço `Spooler` está desligado. Solução: abra o **PowerShell** como administrador e cole o comando de ativação.",
    "section_2_subtitle_1": "📋 Lista de serviços básicos que o Modo Turbo altera",
    "section_3_title": "📋 Outros serviços que você pode encontrar desativados",
    "section_3_intro": "Nem todos aparecem em todas as versões do Windows. Se precisar, ative com o comando abaixo (PowerShell como administrador).",
    "section_4_title": "🕒 Serviços em ‘pausa’ (Manual): iniciam sozinhos quando necessários",
    "section_4_intro": "Esses serviços ficam como 'Manual', ou seja, o Windows inicia automaticamente apenas quando algum app ou recurso solicita, economizando recursos na inicialização. Se preferir que estejam sempre prontos, force o modo Automático:",
    "section_5_title": "🗑️ Desinstalação de aplicativos e componentes",
    "section_5_intro": "O Modo Turbo também remove alguns apps e componentes pré-instalados considerados ‘bloatware’ para deixar o sistema mais leve. Aqui explico o que é removido e como recuperar.",
    "section_5_subtitle_1": "Apps (Clima, Microsoft 365, Teams, To-Do)",
    "section_5_apps_desc": "Função: São aplicativos da Microsoft que vêm com o Windows. São removidos para limpar o menu Iniciar e liberar espaço.<br>Reativação: Pesquise e instale de graça pela <a href=\"https://www.microsoft.com/pt-br/store/apps/windows\" target=\"_blank\" class=\"external-link\">Microsoft Store</a>.",
    "section_5_subtitle_2": "Microsoft Edge e seu Bloqueio de Reinstalação",
    "section_5_edge_desc": "Função: O Edge é removido caso você prefira outro navegador e não queira que ele consuma recursos.<br>Reativar Edge: baixe o instalador na <a href=\"https://www.microsoft.com/pt-br/edge\" target=\"_blank\" class=\"external-link\">página oficial do Microsoft Edge</a>.",
    "section_5_edge_block_desc": "Bloqueio de Reinstalação: O Modo Turbo ativa um bloqueio no Registro para evitar que o Windows Update reinstale o Edge. Para desativar e permitir as atualizações, execute o comando abaixo no PowerShell como administrador:",
    "important_note_title": "🚨 Importante: Variabilidade no Windows!",
    "important_note_content": "Nem todos os serviços existem em todas as versões do Windows. O Windows 7, 10 e 11 não possuem exatamente os mesmos recursos, e também mudam entre edições (Home, Pro, Enterprise) e entre builds/atualizações. **Se você executar um comando e aparecer erro dizendo que o serviço não existe, tudo bem:** ele simplesmente não está presente no seu Windows. **Dica:** reative apenas o que realmente precisar."
,
    "article_win11_25h2_back_to_all": "← Voltar para todos os artigos",

    "section_win11_25h2_1_p1": "A principal novidade chega via Editor de Política de Grupo. Se você usa Windows 11 Pro, pressione Win + R, digite gpedit.msc e tecle Enter.",
    "section_win11_25h2_1_p2": "No Editor de Política de Grupo:",
    "section_win11_25h2_1_li1": "Vá em <span class=\"font-semibold\">Configuração do Computador → Modelos Administrativos → Componentes do Windows</span>.",
    "section_win11_25h2_1_li2": "Encontre a nova opção chamada <span class=\"font-semibold\">Remover aplicativos pré-instalados</span>.",
    "section_win11_25h2_1_li3": "Clique duas vezes nela.",
    "section_win11_25h2_1_li4": "Selecione <span class=\"font-semibold\">Habilitado</span>.",
    "section_win11_25h2_1_li5": "Salve as alterações.",
    "section_win11_25h2_1_li6": "Reinicie o PC. Pronto! Agora você pode desinstalar apps como Paint, Media Player, Cortana, Sticky Notes etc. diretamente nas Configurações.",
    "section_win11_25h2_1_p3": "Se você usa Windows 11 Home, o Editor de Política de Grupo não está disponível oficialmente. Há métodos não suportados para habilitá-lo ou editar o registro, mas não são recomendados para iniciantes.",

    "section_win11_25h2_2_p1": "O processo é simples para usuários do Windows 11 Pro. Basta usar o Editor de Política de Grupo e habilitar a opção para remover aplicativos pré-instalados.",
    "section_win11_25h2_2_p2": "<span class=\"font-semibold\">Configuração do Computador > Componentes do Windows > Implantação de Pacotes de Aplicativos</span>",
    "section_win11_25h2_2_p3": "Para usuários do Windows 11 Home, ainda não há solução oficial. Recomenda-se aguardar atualizações futuras ou usar métodos alternativos com cautela.",
    "section_win11_25h2_2_p4": "<span class=\"font-semibold\">Nota:</span> A disponibilidade desta opção pode variar conforme sua compilação do Windows 11. Certifique-se de estar atualizado.",
    "section_win11_25h2_2_p5": "Após habilitar a política, acesse <span class=\"font-semibold\">Configurações → Aplicativos → Aplicativos instalados</span> e remova os que desejar.",
    "section_win11_25h2_2_p6": "Lembre-se: nem todos os apps podem ser removidos, mas a lista será maior do que nunca.",

    "important_win11_25h2_li1": "Nem todos os aplicativos podem ser desinstalados. Alguns componentes essenciais do sistema permanecerão protegidos.",
    "important_win11_25h2_li2": "Aplicativos como Paint, Media Player, Cortana, Sticky Notes e outros podem ser removidos. Apps do sistema como Explorador de Arquivos, Microsoft Store ou Configurações permanecerão protegidos.",
    "important_win11_25h2_li3": "A disponibilidade pode variar conforme a compilação e a região.",
    "important_win11_25h2_li4": "Sempre faça backup antes de remover aplicativos importantes.",

    "section_win11_25h2_3_p1": "O novo recurso é esperado na atualização do Windows 11 25H2, prevista para o fim de 2025. Usuários do programa Insider podem recebê-lo antes.",
    "section_win11_25h2_4_li1": "Menos bloatware significa um sistema mais limpo, rápido e com mais espaço livre.",
    "section_win11_25h2_4_li2": "Oferece ao usuário mais controle sobre o que permanece instalado no PC.",
    "section_win11_25h2_5_li1": "Além dos aplicativos mencionados, outros podem se tornar removíveis no futuro conforme o Windows evolui.",
    "section_win11_25h2_5_li2": "A lista de apps removíveis pode crescer em futuras atualizações.",
    "section_win11_25h2_5_li3": "Ferramentas de terceiros ainda podem ser úteis para remoções avançadas.",
    "section_win11_25h2_5_li4": "A Microsoft pode reverter ou mudar essa política em compilações futuras.",
    "section_win11_25h2_5_p1": "Fique atento às notícias e sempre leia as notas de versão antes de atualizar.",
    "conclusion_win11_25h2_p1": "A atualização do Windows 11 25H2 marca um passo importante no controle do usuário sobre o sistema.",
    "conclusion_win11_25h2_p2": "Remover bloatware nunca foi tão fácil — e oficial! Aproveite para deixar o Windows com a sua cara.",

    "donations_page_title": "BCDeX: Como a ideia nasceu e quem está por trás do projeto",
    "donations_title": "Torne-se um Parceiro do Projeto",
    "donations_intro": "O BCDeX é gratuito e sempre será graças ao apoio de uma comunidade incrível. Sua contribuição não é apenas uma doação: é um 'soquinho' no projeto que já te poupou de pagar um técnico, perder horas ou comprar ferramentas extras. É investir para que esta ferramenta —feita por um entusiasta para entusiastas— continue existindo e melhorando.",
    "donations_why_title": "Por que seu apoio é tão importante?",
    "donations_why_item1_title": "🚀 Impulsiona novos recursos",
    "donations_why_item1_text": "Sempre que a Microsoft muda algo, é preciso reescrever partes do código do zero. Seu apoio permite dedicar tempo a essas atualizações e desenvolver o que a comunidade pede: mais compatibilidade, mais automação, mais personalização.",
    "donations_why_item2_title": "🛡️ Garante a continuidade do projeto",
    "donations_why_item2_text": "Servidores, domínios, ferramentas de desenvolvimento e testes não são grátis. Sem apoio, o projeto termina como 90% do software útil que morre por falta de suporte. Se a comunidade apoia, o BCDeX continua gratuito, limpo e sem patrocinadores ou spyware.",
    "donations_why_item3_title": "☕ Alimenta a paixão (e o desenvolvedor)",
    "donations_why_item3_text": "Este é um projeto de um único desenvolvedor. Cada doação literalmente vira café, horas de código, correção de bugs e suporte aos usuários. É uma forma de dizer ‘você me ajudou — aqui vai meu soquinho na vida real’.", 
    "donations_why_footer": "Se o BCDeX te ajudou, retribua. Se não, ao menos não deixe que desapareça por falta de apoio.",
    "donations_how_title": "Escolha sua forma de contribuir",
    "donations_how_text": "Cada doação, independentemente do valor, nos ajuda a cobrir custos de desenvolvimento, manutenção e servidores. Obrigado por fazer parte da comunidade BCDeX!",

    "article_instalacion_particion_back_to_all": "← Voltar para todos os artigos",
    "section_instalacion_particion_process_title": "O processo com o BCDeX: Fácil e Rápido",
    "section_instalacion_particion_process_p1": "Instalar o Windows a partir de uma partição do disco é um método extremamente eficiente que o BCDeX automatiza por completo. O processo começa escolhendo o disco onde será criada uma partição temporária e a imagem ISO do Windows que você deseja instalar. O BCDeX é compatível com várias versões, do Windows 7 ao 11, inclusive ISOs modificadas. Uma grande vantagem é ignorar automaticamente as verificações de TPM e Secure Boot, facilitando a instalação do Windows 11 em hardware não compatível.",
    "section_instalacion_particion_process_p2": "Ao clicar em \"Avançar\", o app cuida de tudo: cria a partição, monta a ISO e copia os arquivos de instalação. O processo é totalmente desassistido até o próximo passo.",
    "section_instalacion_particion_custom_title": "Personalização e Otimização (Opcional)",
    "section_instalacion_particion_custom_p1": "Antes de reiniciar, o BCDeX oferece um de seus recursos mais poderosos: a personalização da instalação. Você pode criar um usuário local, pular a configuração de rede durante o OOBE, reduzir telemetria e desinstalar bloatware. Assim você tem um sistema mais limpo, rápido e privado desde a primeira inicialização.",
    "section_instalacion_particion_install_cleanup_title": "Instalação e Limpeza Final",
    "section_instalacion_particion_install_p1": "Com tudo pronto, o aplicativo pedirá para reiniciar. Ao fazer isso, o sistema iniciará automaticamente no ambiente de instalação do Windows preparado pelo BCDeX. Se não iniciar, selecione a entrada \"BCDeX Boot\" no menu de boot do seu PC.",
    "important_note_instalacion_particion_title": "💡 Importante:",
    "important_note_instalacion_particion_p1": "Durante a instalação do Windows, você verá uma partição chamada <strong>\"BCDeX Vol\"</strong>. É crucial que <strong>não a exclua</strong>, pois ela contém todos os arquivos necessários para concluir a instalação.",
    "section_instalacion_particion_cleanup_p1": "Quando o novo Windows estiver funcionando, o último passo é a limpeza. Execute o BCDeX novamente (na partição temporária) e escolha \"Desfazer alterações\". Isso removerá a partição de instalação, liberando espaço e deixando o sistema impecável.",
    "page_title_article_sobre_el_creador": "BCDeX: Como a ideia nasceu e quem está por trás do projeto",
    "article_sobre_el_creador_back_link": "← Voltar para todos os artigos",
    "article_sobre_el_creador_summary": "Olá, eu sou o José 'PadeX' 👋 e se você está lendo isso, provavelmente já conhece meu aplicativo BCDeX, ou pelo menos parece familiar. Neste post, quero contar um pouco da história por trás do projeto. Porque sim, embora possa parecer um aplicativo mágico que aparece na sua área de trabalho e cria uma partição inicializável como por mágica... por trás há muitas noites sem dormir, testes fracassados e litros de café ☕.",
    "section_sobre_el_creador_1_title": "Tudo começou por causa dos 'WeSeBes'... e um script",
    "section_sobre_el_creador_1_p1": "Tudo começou quando um dia, depois de instalar o Windows pela enésima vez em diferentes PCs (alguns sem portas USB funcionais, outros com BIOS que não aceitam inicialização por USB, outros com UEFI super restritivos...), eu disse a mim mesmo:",
    "section_sobre_el_creador_1_quote1": "“Por que isso tem que ser tão complicado? E se eu criar uma maneira de instalar o Windows <br>do mesmo disco rígido, sem pendrives, sem DVDs e sem tanto trabalho?”",
    "section_sobre_el_creador_1_p2": "Foi assim que comecei criando um pequeno script em PowerShell que simplesmente criava uma partição secundária no disco para atuar como um “lançador” para a instalação do Windows. Parecia uma boa ideia, até que percebi algo: era preciso montar a ISO manualmente, copiar os arquivos um por um... e isso para muitos usuários era uma dor de cabeça.",
    "section_sobre_el_creador_1_p3": "Aí me lembrei de uma frase que um professor me repetia nos meus anos de estudo:",
    "section_sobre_el_creador_1_quote2": "“Vocês devem aprender a programar para leigos.”",
    "section_sobre_el_creador_1_p4": "E ele não dizia isso de forma ofensiva. O que ele queria dizer era que, ao desenvolver algo, é preciso pensar absolutamente tudo do ponto de vista do usuário final, inclusive daquele que não tem a menor ideia de informática. A experiência tem que ser tão simples que qualquer um possa fazê-lo sem ler um manual.",
    "section_sobre_el_creador_1_p5": "Essa frase me marcou. E eu me propus: “Como posso fazer para que o usuário nem precise montar a ISO?”",
    "section_sobre_el_creador_2_title": "Aprendendo na marra (e com o Google)",
    "section_sobre_el_creador_2_p1": "Foi assim que comecei a trabalhar na automação da cópia da ISO diretamente do PowerShell. Sem necessidade de montá-la, sem passos estranhos. Spoiler: não foi fácil. Tive que ler bastante sobre estruturas de arquivos ISO, WIMs, extrair conteúdo diretamente sem unidades virtuais… mas no final consegui que tudo fosse feito automaticamente.",
    "section_sobre_el_creador_2_p2": "Até aí tudo bem. Mas me deparei com outro problema: o console do PowerShell não é exatamente o mais amigável para muitos usuários. Intimida, dá erros em vermelho, e não é tão claro o que fazer se algo falhar.",
    "section_sobre_el_creador_2_p3": "Então decidi dar o próximo passo: criar uma interface gráfica simples, mas funcional, que guiasse o usuário em todo o processo —desde a criação da partição até a cópia da ISO e a configuração da inicialização.",
    "section_sobre_el_creador_2_p4": "Aí nasceu o que hoje é o <strong>BCDeX</strong>.",
    "section_sobre_el_creador_3_title": "E de onde vem o nome \"BCDeX\"?",
    "section_sobre_el_creador_3_p1": "Quando o aplicativo começou a tomar forma, eu precisava de um nome. Algo que refletisse o que ele fazia, mas que também tivesse um pouco de identidade pessoal.",
    "section_sobre_el_creador_3_p2": "Foi aí que me ocorreu combinar duas coisas: BCD, pelo famoso Boot Configuration Data que o aplicativo manipula para criar as entradas de inicialização do Windows... e PadeX, que é o nome do meu canal no YouTube, onde compartilho muitos desses projetos.",
    "section_sobre_el_creador_3_p3": "Assim nasceu o nome BCDeX: uma fusão do técnico e do pessoal. 😄",
    "section_sobre_el_creador_4_title": "E quem está por trás?",
    "section_sobre_el_creador_4_p1": "Como eu disse antes, eu sou o PadeX, e sim, eu faço de tudo: programador, designer, testador, criador de conteúdo e até suporte técnico nos comentários dos meus vídeos 😅.",
    "section_sobre_el_creador_4_p2": "Tudo o que você vê neste site, no canal do YouTube e no aplicativo, sou eu quem faço (por enquanto). Com erros, com melhorias contínuas e com muita vontade de continuar avançando.",
    "section_sobre_el_creador_4_p3": "O BCDeX não é apenas uma ferramenta. É o resultado de muitos testes, fracassos, aprendizados e, acima de tudo, de uma obsessão por facilitar a vida de quem quer instalar o Windows sem complicações.",
    "section_sobre_el_creador_5_title": "O que vem a seguir?",
    "section_sobre_el_creador_5_p1": "Continuar melhorando. Quero integrar novas funções, como otimizações pós-instalação, mais compatibilidade e uma ou outra surpresa pensada para deixar seu Windows pronto e afinado desde o primeiro início.",
    "section_sobre_el_creador_5_p2": "É por isso que o apoio e as contribuições de quem usa o aplicativo também são tão importantes. Graças a isso, posso continuar mantendo o site, atualizando a ferramenta e dedicando tempo para melhorá-la constantemente.",
    "section_sobre_el_creador_5_p3": "E se você tiver interesse em saber mais ou dar ideias, convido você a me seguir nas redes sociais, no <a href=\"https://www.youtube.com/@PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">YouTube</a>, <a href=\"https://www.instagram.com/padexchn/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Instagram</a>, <a href=\"https://www.tiktok.com/@padexch\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">TikTok</a>, <a href=\"https://x.com/PadeXchn\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">X</a>, <a href=\"https://www.facebook.com/PadeXch/\" target=\"_blank\" rel=\"noopener\" class=\"external-link\">Facebook</a> e deixar um comentário por lá.",
    "section_sobre_el_creador_5_p4": "Obrigado por fazer parte disso. 💙",
    "section_sobre_el_creador_5_p5": "— <strong>PadeX</strong> 💻",
    "download_page_title": "BCDeX - Download",
    "download_header_title": "Baixar BCDeX",
    "download_header_subtitle": "Você está a um clique de simplificar suas instalações do Windows para sempre.",
    "download_v23_title": "Versão 2.3",
    "download_updated_on_label": "Atualizado em:",
    "download_features_title": "Principais Características",
    "download_v23_b1": "Compatível com <strong>Windows 7</strong>, <strong>8</strong>, <strong>8.1</strong>, <strong>10</strong> e <strong>11</strong>",
    "download_v23_b2": "Criação de unidades <strong>USB inicializáveis</strong>",
    "download_v23_b3": "<strong>Modo Turbo</strong>: Desativa serviços raramente usados para liberar recursos do sistema",
    "download_v23_b4": "Suporte para inicialização <strong>UEFI</strong> e <strong>Legacy</strong>",
    "download_v23_b5": "<strong>100% seguro e livre de malware</strong>",
    "download_links_title": "Links para Download",
    "download_server_1": "⬇️ Servidor #1",
    "download_server_2": "⬇️ Servidor #2",
    "download_server_3": "⬇️ Servidor #3",
    "download_changes_title": "Mudanças nesta versão",
    "download_changes_text": "Melhorias de desempenho e estabilidade foram implementadas.",
    "download_win7_compat_title": "Compatibilidade com Windows 7",
    "download_win7_compat_desc": "Pacote .rar com instaladores do .NET Framework 4.0 e atualizações cumulativas x86/x64 necessárias para executar o BCDeX no Windows 7.",
    "download_win7_package_btn": "Baixar pacote do Windows 7",
    "download_v13_title": "Versão 1.3",
    "download_v13_b1": "Compatível com Windows 8, 10 e 11",
    "download_v13_b2": "Suporte para inicialização UEFI e Legacy",
    "download_v13_b3": "100% seguro e livre de malware",
    "download_warning_title": "Aviso Importante",
    "download_warning_text": "O BCDeX é uma ferramenta destinada a usuários com alguma experiência. Embora tenhamos projetado o aplicativo com muito cuidado, o uso incorreto pode afetar o sistema. Recomendamos seguir as instruções e usá-lo com critério. Para mais informações, consulte nossos <a href=\"terminos.html\" class=\"text-red-600 hover:underline\">Termos e Condições</a>.",
    "download_contact_text": "Se você tiver problemas com o download ou alguma sugestão, não hesite em <a href=\"contacto.html\" class=\"text-red-600 hover:underline\">nos contatar</a>.",

    "contact_page_title": "Contato",
    "contact_title": "Contato",
    "contact_intro": "Tem dúvidas, sugestões ou precisa de suporte?",
    "contact_intro_secondary": "Estas são as melhores formas de falar com a gente:",
    "contact_youtube": "YouTube",
    "contact_facebook": "Facebook",
    "contact_discord": "Discord",
    "contact_email": "Email",
    "contact_tiktok": "TikTok",
    "contact_instagram": "Instagram",
    "contact_x": "X",
    "contact_support_title": "Apoie o projeto",
    "contact_support_text": "Toda contribuição, grande ou pequena, ajuda a continuar melhorando o BCDeX para toda a comunidade.",
    "contact_support_button": "Ver opções de doação"
}